### PR TITLE
[AMDGPU] Disable d16 loads/stores to high register halves on gfx90a

### PR DESCRIPTION
**Pull request by krzysz00**
Testing reveals that, on gfx90a, *_load_short_d16_hi does note
preserve the low-order bits of the destination register, even with
SramECC disabled. To prevent the generation of semantically incorrect
code, disable D16PreservesUnesedBits on this target.

(A more specific test may be needed to account for future gfx90*
targets, but checking for gfx90a instructions was what was in the
existing code)

Internal note: This patch causes the PR E2E tests to pass on Lockhart, resolving https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/363, and I'll be sending it upstream shortly.

### CODE REVIEW

**Comment by krzysz00** [comment]
https://reviews.llvm.org/D112635 is the upstream version

**Comment by krzysz00** [comment]
(and since I'm getting review upstream, drafting this)

**Comment by whchung** [comment]
@krzysz00 I guess this PR is no longer need? I just saw you closed D112635 upstream.

**Comment by krzysz00** [comment]
Yeah, we have a better workaround in the form of a kernel parameter and there's a fix being worked on by the driver team, closing.

**Pull request closed without merging**
