### PR TITLE
Correct BF16 arithmetic lowering

### PR DESCRIPTION
**Pull request by krzysz00**

### CODE REVIEW

**Comment by whchung** [comment]
should we add tests to this PR?

**Comment by krzysz00** [comment]
@whchung I was thinking it might make more sense to add the testing during a followup PR, since what's mainly missing is bf16 e2e tests

**Comment by whchung** [comment]
SGTM.

**Review by whchung — APPROVED** [review]
Let's get this PR in and use a follow-up PR to add e2e tests.

**Pull request merged**
