### PR TITLE
Bring up Ubuntu 20.04 + ROCm 5.3.2

### PR DESCRIPTION
**Pull request by jerryyin**

### CODE REVIEW

**Review by krzysz00 — APPROVED** [review]
LGTM. Have you tested this manually with something like

```
docker build -t ubuntu-20-04-test -f ./mlir/utils/jenkins/Dockerfile.rocm ./mlir/utils/jenkins
```
from the repo root?

**Comment by jerryyin** [comment]
@krzysz00 I have tested through local checks as well as static lib generation manually.

> docker build -t ubuntu-20-04-test -f ./mlir/utils/jenkins/Dockerfile.rocm ./mlir/utils/jenkins

How does it work? You can just execute jenkinsfile by just referencing its location from `./mlir/utils/jenkins`?

**Comment by krzysz00** [comment]
@jerryyin That's not executing Jenkins, that's just building the Docker container locally.

And then you give it a name so you can try to run stuff inside of it if you'd like

**Comment by jerryyin** [comment]
@krzysz00 Okay I was confused because of that additional directory followed in it. After the `-f` option, you can get rid of that `Dockerfile.rocm` because it is gone now, just FYI.

**Pull request merged**
