### PR TITLE
MLIR#283: llvm update 9-6-21

### PR DESCRIPTION
**Pull request by sjw36**
* many similar std and dialect ops consolidated into memref dialect (alloc/dealloc/load/store/cast/reshape/subview/etc)
    * moved math::<utility_funcs> to math_util namespace
    * changed tosa-to-miopen to use memref.expand_shape
    * minor refactor of RewritePatterns
    * Much of BackendUtils is superceded by SerializeToHsaco
    * updated tools for new SerializeToHsaco
    * alot of test updates for memref dialect
    * gpu-to-rocdl now requires gpu.func (vs func)

In LLVM subtree:

    * cleanup printers for miopen specific ops
    * fixed SerializeToHsaco for target triple, chip, features
    * Added back vector.tuple and vector.tuple_get impls
    * Added mlir::registerToROCDLIRTranslation for -mlir-to-rocdlir

### CODE REVIEW

**Comment by sjw36** [comment]
The relevant changes for us are mostly in the last 4 commits.

@krzysz00 we should probably run all test suites.

@jerryyin I don't this this should affect miopen integration but check out the SerializeToHsaco changes.

@whchung there were some vector ops removed (tuple and tuple_get). I readded them but we should look at refactoring.

**Comment by sjw36** [comment]
And please prioritize this over other PRs to minimize conflicts.

**Comment by sjw36** [comment]
jenkins: retest this please

**Comment by sjw36** [comment]
The spirit of the test should still be correct, testing our GPU Dialect operation conversions to ROCDL. There appear to be issues with vector.type_cast when index-bitwidth=32.

**Comment by sjw36** [comment]
@krzysz00 I do not understand why this failed. Can you check and restart if it is a system problem. Thanks.

**Comment by sjw36** [comment]
Well, this one looks bad...  Error in LLVM backend (RA).

> error: register rewriting failed: cycle in copy bundle

This test was passing for me a few days ago.. not sure what changed.

@whchung have you run into this issue? any ideas?

**Comment by whchung** [comment]
Unfortunately I haven’t encountered this issue before. :(

**Comment by sjw36** [comment]
> Unfortunately I haven’t encountered this issue before. :(

Bummer. Our generated code is identical...

**Comment by sjw36** [comment]
@krzysz00 any idea why this is taking so long? My local tests take about 40 min..

**Comment by krzysz00** [comment]
@sjw36 No clue, sorry, that's pretty weird. However, try manually building the tests without xdlops to make sure this isn't reproducable.

**Comment by sjw36** [comment]
Any idea why this is still running??? My local run is done ~40 min..

**Comment by jerryyin** [comment]
@sjw36 I took a look at your jenkins task: When you push a newer commit, you'll have to manually go to jenkins to stop the older ones. Otherwise this will trigger multiple jenkins runs and make a resource contention. I just manually go in and stopped multiple running test on commit c7d9791 and kicked off a new run.

**Comment by jerryyin** [comment]
Once all CI passed, please trigger another nightly test according to [here](https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/342). Because of the scale of this PR, we should merge only if we can guarantee nightly is passing.

**Comment by sjw36** [comment]
@jerryyin there seems to be an old build/test (11) that was started 4 days ago. I cannot kill it thru the web interface. Can you kill it?

**Comment by jerryyin** [comment]
@sjw36 I have tried to put a stop on that but somehow it is still running now. Just tried again.

>  I cannot kill it thru the web interface. 

Please log on with your NT ID, you should have permission to this CI automatically.

**Comment by sjw36** [comment]
I am going to close this since it keeps getting stuck in build/test. I will create a new PR.

**Pull request closed without merging**
