### PR TITLE
Add support for tuning split-k with convolutions

### PR DESCRIPTION
**Pull request by djramic**
Added the **enable_splitk_for_tuning** attribute to the convolution func to enable tuning of various split-k values.

### CODE REVIEW

**Review by krzysz00 — APPROVED** [review]
Seems fine

**Comment by krzysz00** [comment]
... then again, hold on, now that MIGraphX has split-K, shouldn't we be removing the attribute like the TODOs say?

**Comment by pfultz2** [comment]
We dont have it enabled by default in migraphx yet.

**Review by manupak — CHANGES_REQUESTED** [review]
This PR is approved but putting a blocker until https://github.com/ROCm/rocMLIR-internal/issues/1570 is done, as discussed.

Please feel free to use this commits in the next PR.
This is to guard our CI blowing up.

**Comment by dhernandez0** [comment]
I'm closing this because https://github.com/ROCm/rocMLIR/pull/1616 was merged.

**Pull request closed without merging**
