### PR TITLE
Fix unit test padding_kernel_gemmN.

### PR DESCRIPTION
**Pull request by whchung**
PR #264 broke nightly CI:

http://ml-ci.amd.com:21096/job/MLIR/job/check-mlir-nightly/83/console

Luckily it seems it's just a poorly written unit test.

### CODE REVIEW

**Comment by whchung** [comment]
@okakarpa `default` CI target is always failing it seems.

**Comment by okakarpa** [comment]
> @okakarpa `default` CI target is always failing it seems.

Is it ok if i make sure Public and private ci are following the same ci pattern

**Comment by whchung** [comment]
> Is it ok if i make sure Public and private ci are following the same ci pattern

Could you define what `CI pattern` is? I don't know too much about it.

**Comment by okakarpa** [comment]
> > Is it ok if i make sure Public and private ci are following the same ci pattern
> 
> Could you define what `CI pattern` is? I don't know too much about it.

As of the now the private Jenkins(rocmhead) follows the Multi-branch deployment model if for some reason if the job fails i have an ability to retrigger the job by slecting the PR number 

http://10.236.106.97:8080/job/mlir/view/change-requests/ (Private-jenkins)

For public Jenkins (ml-ci/default) the job is triggered through GitHub web-hooks dependent on Pull request builder plugin  I don't have the ability to retrigger the job through jenkins i need to push an empty commit to PR to run the job again 

http://ml-ci.amd.com:21096/job/MLIR/job/MLIR-downstream-unit-test/

**Comment by whchung** [comment]
> > > Is it ok if i make sure Public and private ci are following the same ci pattern
> > 
> > 
> > Could you define what `CI pattern` is? I don't know too much about it.
> 
> As of the now the private Jenkins(rocmhead) follows the Multi-branch deployment model if for some reason if the job fails i have an ability to retrigger the job by slecting the PR number
> 
> http://10.236.106.97:8080/job/mlir/view/change-requests/ (Private-jenkins)
> 
> For public Jenkins (ml-ci/default) the job is triggered through GitHub web-hooks dependent on Pull request builder plugin I don't have the ability to retrigger the job through jenkins i need to push an empty commit to PR to run the job again
> 
> http://ml-ci.amd.com:21096/job/MLIR/job/MLIR-downstream-unit-test/

Understood. Thanks for the explanation. I'm fine if both sites follow the same pattern. I imagine the Multi-branch deployment model suits you better?

**Review by asleepzzz — APPROVED** [review]
just add space

**Pull request merged**
