### PR TITLE
Enabled f16 support for the split-K GEMM scheme

### PR DESCRIPTION
**Pull request by ravil-mobile**
This PR depends on: https://github.com/ROCm/rocMLIR/pull/1451

### CODE REVIEW

**Comment by ravil-mobile** [comment]
Here are some first tuning results:

## MI200

```bash
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 154 -n 166400 -k 2048 -t f16 -out_datatype f16', perfConfig = v2:256,256,4,128,128,4,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2 -n 1280 -k 2816 -t f16 -out_datatype f16', perfConfig = v2:64,128,4,64,32,4,30,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2 -n 1280 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:64,64,4,32,32,4,27,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2 -n 1280 -k 320 -t f16 -out_datatype f16', perfConfig = v2:32,64,4,16,64,4,20,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2 -n 13760 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:64,256,2,64,64,4,4,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA true -transB false -g 1 -m 8192 -n 640 -k 640 -t f16 -out_datatype f16', perfConfig = v2:128,128,8,64,64,4,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 8192 -n 1920 -k 640 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,64,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 8192 -n 640 -k 640 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,64,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 8192 -n 5120 -k 640 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,64,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 8192 -n 640 -k 2560 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,64,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA true -transB false -g 1 -m 2048 -n 1280 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:128,64,8,64,32,4,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2048 -n 3840 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,64,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2048 -n 1280 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:128,64,8,32,64,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2048 -n 10240 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,64,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2048 -n 1280 -k 5120 -t f16 -out_datatype f16', perfConfig = v2:128,64,8,32,64,8,1,1,1
```

| Config | wo split-k, TFLOP/s | w split-k, TFLOP/s | speed-up | Best Split Factor |
| ---------|---------|---------|---------|---------|
|  -g 1 -m 2 -n 1280 -k 2816    | 0.42108 | 1.09893 |     2.610        |      30       |
|  -g 1 -m 2 -n 1280 -k 1280    | 0.31511 |  0.69424 |     2.201        |       16     |
|  -g 1 -m 2 -n 1280 -k 320      | 0.14423 | 0.21787  |      1.510       |       7      |
|  -g 1 -m 2 -n 13760 -k 1280  | 2.01070 |   2.0386 |     1.001        |         4   |


| Config | wo split-k | w split-k |
| ---------|---------|---------|
|  -g 1 -m 2 -n 1280 -k 2816 | 32,32,8,16,16,8,1,1 | v2:8,128,4,4,64,8,30,1,1 |
|  -g 1 -m 2 -n 1280 -k 1280 | 32,32,8,16,16,8,1,1 | v2:32,32,4,16,16,4,16,1,1 |
|  -g 1 -m 2 -n 1280 -k 320   | 32,32,8,16,16,8,1,1 | v2:32,64,4,32,32,4,7,1,1 |
|  -g 1 -m 2 -n 13760 -k 1280      | 32,32,4,16,16,8,1,1 | v2:8,256,4,8,64,8,4,1,1 |

**Comment by ravil-mobile** [comment]
Here are results with split-K update - i.e. two way padding

## MI200

| Config | wo split-k, TFLOP/s | w split-k, TFLOP/s | speed-up | Best Split Factor |
| ---------|---------|---------|---------|---------|
|  -g 1 -m 2 -n 1280 -k 2816    | 0.42108 | 1.1124938 |     2.6420        |      30       |
|  -g 1 -m 2 -n 1280 -k 1280    | 0.31511 |  0.706206 |     2.24114        |       21     |
|  -g 1 -m 2 -n 1280 -k 320      | 0.14423 | 0.238139  |      1.65110       |       11      |
|  -g 1 -m 2 -n 13760 -k 1280  | 2.01070 |   1.95697 |     0.97327       |         22   |


| Config | wo split-k | w split-k |
| ---------|---------|---------|
|  -g 1 -m 2 -n 1280 -k 2816 | 32,32,8,16,16,8,1,1 | v2:32,128,4,32,32,8,30,1,1 |
|  -g 1 -m 2 -n 1280 -k 1280 | 32,32,8,16,16,8,1,1 | v2:32,128,4,32,32,8,21,1,1 |
|  -g 1 -m 2 -n 1280 -k 320   | 32,32,8,16,16,8,1,1 | v2:4,128,8,4,64,4,11,1,1 |
|  -g 1 -m 2 -n 13760 -k 1280      | 32,32,4,16,16,8,1,1 | v2:8,256,4,8,64,8,22,1,1 |

**Comment by ravil-mobile** [comment]
Hi @giuseros 

Here are updated results based on the latest changes in `fix_atomic_fadd_fp16` and `ravil/split-k-config`

## MI200

| Config | wo split-k, TFLOP/s | w split-k, TFLOP/s | speed-up | Best Split Factor |
| ---------|---------|---------|---------|---------|
|  -g 1 -m 2 -n 1280 -k 2816    | 0.42108 | 1.024 |     2.431        |      31      |
|  -g 1 -m 2 -n 1280 -k 1280    | 0.31511 |   0.66064 |     2.096        |       26     |
|  -g 1 -m 2 -n 1280 -k 320      | 0.14423 |  0.2226  |      1.543       |       11      |
|  -g 1 -m 2 -n 13760 -k 1280  | 2.01070 |   2.06723 |     1.028     |         24   |


| Config | wo split-k | w split-k |
| ---------|---------|---------|
|  -g 1 -m 2 -n 1280 -k 2816 | 32,32,8,16,16,8,1,1 | v2:32,128,8,32,32,4,31,1,1 |
|  -g 1 -m 2 -n 1280 -k 1280 | 32,32,8,16,16,8,1,1 | v2:32,64,8,8,64,4,26,1,1 |
|  -g 1 -m 2 -n 1280 -k 320   | 32,32,8,16,16,8,1,1 | v2:128,64,8,64,32,4,11,1,1 |
|  -g 1 -m 2 -n 13760 -k 1280      | 32,32,4,16,16,8,1,1 | v2:8,256,4,8,64,8,24,1,1 |

**Comment by ravil-mobile** [comment]
Hi @giuseros 

Here are yet another updated results based on the latest changes in `fix_atomic_fadd_fp16` and `develop`

## MI200

| Config | wo split-k, TFLOP/s | w split-k, TFLOP/s | speed-up | Best Split Factor |
| ---------|---------|---------|---------|---------|
|  -g 1 -m 2 -n 1280 -k 2816    | 0.42108 | 0.9012 |     2.140        |      25      |
|  -g 1 -m 2 -n 1280 -k 1280    | 0.31511 |   0.6501 |     2.063        |       24     |
|  -g 1 -m 2 -n 1280 -k 320      | 0.14423 |  0.2327  |      1.6134       |       4      |
|  -g 1 -m 2 -n 13760 -k 1280  | 2.01070 |   2.057 |     1.028     |         1   |


| Config | wo split-k | w split-k |
| ---------|---------|---------|
|  -g 1 -m 2 -n 1280 -k 2816 | 32,32,8,16,16,8,1,1 | v2:16,16,4,16,16,4,25,1,1 |
|  -g 1 -m 2 -n 1280 -k 1280 | 32,32,8,16,16,8,1,1 | v2:16,16,4,16,16,8,24,1,1 |
|  -g 1 -m 2 -n 1280 -k 320   | 32,32,8,16,16,8,1,1 | v2:16,32,8,16,16,4,4,1,1 |
|  -g 1 -m 2 -n 13760 -k 1280      | 32,32,4,16,16,8,1,1 | v2:32,64,8,32,16,4,1,1,1 |

The new heuristic used the Data Parallel Scheme for `  -g 1 -m 2 -n 13760 -k 1280 ` configuration.

**Comment by ravil-mobile** [comment]
# Updated results on MI200

```cpp
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 154 -n 166400 -k 2048 -t f16 -out_datatype f16', perfConfig = v2:256,256,8,128,16,4,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2 -n 1280 -k 2816 -t f16 -out_datatype f16', perfConfig = v2:128,64,8,128,16,8,8,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2 -n 1280 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:16,16,8,16,16,4,25,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2 -n 1280 -k 320 -t f16 -out_datatype f16', perfConfig = v2:64,64,8,32,32,8,8,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2 -n 13760 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:32,256,2,32,32,4,5,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA true -transB false -g 1 -m 8192 -n 640 -k 640 -t f16 -out_datatype f16', perfConfig = v2:128,128,8,64,32,4,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 8192 -n 1920 -k 640 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,32,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 8192 -n 640 -k 640 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,32,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 8192 -n 5120 -k 640 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,32,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 8192 -n 640 -k 2560 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,32,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA true -transB false -g 1 -m 2048 -n 1280 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:128,64,8,64,32,4,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2048 -n 3840 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,32,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2048 -n 1280 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:128,64,8,32,32,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2048 -n 10240 -k 1280 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,128,16,8,1,1,1
Arch = gfx90a:sramecc+:xnack-(110 CUs), vector = '-transA false -transB false -g 1 -m 2048 -n 1280 -k 5120 -t f16 -out_datatype f16', perfConfig = v2:128,128,4,64,32,8,2,1,1
```


| Config | wo split-k, TFLOP/s | w split-k, TFLOP/s | speed-up | Best Split Factor |
| ---------|---------|---------|---------|---------|
|  -g 1 -m 2 -n 1280 -k 2816    | 0.42108 | 0.92898 |     2.206        |      8       |
|  -g 1 -m 2 -n 1280 -k 1280    | 0.31511 |  0.64 |     2.0310        |       25     |
|  -g 1 -m 2 -n 1280 -k 320      | 0.14423 | 0.21787  |      1.511       |       8      |
| -g 1 -m 2 -n 13760 -k 1280   | 2.01070 | 1.96571  |      0.978       |      5      |
|  -g 1 -m 2048 -n 1280 -k 5120  | 102.9285 |  109.513 |     1.064       |         2   |


| Config | wo split-k | w split-k |
| ---------|---------|---------|
|  -g 1 -m 2 -n 1280 -k 2816 | 32,32,8,16,16,8,1,1 | v2:128,64,8,128,16,8,8,1,1 |
|  -g 1 -m 2 -n 1280 -k 1280 | 32,32,8,16,16,8,1,1 | v2:16,16,8,16,16,4,25,1,1 |
| -g 1 -m 2 -n 1280 -k 320   | 32,32,8,16,16,8,1,1 | v2:64,64,8,32,32,8,8,1,1 |
| -g 1 -m 2 -n 13760 -k 1280   | 32,32,8,16,16,8,1,1 | v2:32,256,2,32,32,4,5,1,1 |
|  -g 1 -m 2048 -n 1280 -k 5120      | 64,128,8,32,16,4,1,1 | v2:128,128,4,64,32,8,2,1,1 |

**Comment by giuseros** [comment]
These are the perf difference with/without split-k for sdxl gemms

So there are 4 configs where split-k is used, and 3 of them get a very good speed-up (between 13% and 150%). 

There is one config where we get a speed up even without split-k, but I think this is a tuning stability issue. 

[splitk.zip](https://github.com/ROCm/rocMLIR/files/14771681/splitk.zip)

All in all I think performance are in check. The only thing that worries me a bit is that we are increasing by a lot the tuning time. We should really get down to find heuristics to drive the tuner in order to avoid spending ages in tuning.

**Review by giuseros — APPROVED** [review]
LGTM

**Pull request merged**
