### PR TITLE
Add reboot in post build action

### PR DESCRIPTION
**Pull request by jerryyin**
This will help get rid of zombie process after mlir execution in each parallel stage.

### CODE REVIEW

**Comment by yiqian1** [comment]
Normally how long does it take to reboot? 3-5min?

**Comment by jerryyin** [comment]
@yiqian1 It won't matter because all the reboot are at the end of the parallel step, so has no impact on execution of the stages themselves. The benefit it bring is that when jenkins pick up the machine to execute the next job, it guaranteed to have no zombie process.

**Comment by okakarpa** [comment]
> Normally how long does it take to reboot? 3-5min?

The node should be back online in 5 mins unless there is an issue with hardware

**Comment by yiqian1** [comment]
> 
Have you tested the change?

The reboot will kill all processes including the current jenkins process. Will the current jenkins process notify next step that "this step is done" before it gets killed?

**Comment by jerryyin** [comment]
> The reboot will kill all processes including the current jenkins process. Will the current jenkins process notify next step that "this step is done" before it gets killed?

I'm not sure I get the question: The reboot only happens when the stage chain ends. What do you expect jenkins to do when the stage chain ends? There's no next step when it needs to reboot on the particular jenkins slave.

**Review by okakarpa — APPROVED** [review]

**Pull request merged**
