### PR TITLE
Make libMLIRMIOpen installation a separate step

### PR DESCRIPTION
**Pull request by krzysz00**
Define BUILD_FAT_LIBMLIRMIOPEN, which controls whether to create the
libMLIRMIOpenn.a static library. Also, don't copy it to /opt/rocm by
default, but instead define an installation component.

Also update the Jenkinsfiles to pass in the new flag, and update the
top level CMakeLists.txt to make BUILD_FAT_LIBMLIRMIOPEN define
subsidiary settings.

### CODE REVIEW

**Comment by krzysz00** [comment]
jenkins: retest this please

**Review by jerryyin — APPROVED** [review]
LGTM. Please rebase to catch up with the tip.

Also, do let me know before you hit the merge button as this will change the client behavior. I will need to immediately submit another PR in the models repo to make sure their end is not broken.

**Comment by krzysz00** [comment]
@jerryyin This will change the installation behavior for libMLIRMIOpen, yes.

Do you want me to send you a Teams message when I'm about to merge?

**Comment by jerryyin** [comment]
@krzysz00 On a second thought, hold it and let me click the merge button.

**Pull request merged**
