### PR TITLE
Change ROCm version from 4.0 to 4.1.1.

### PR DESCRIPTION
**Pull request by pcf000**
4.1.1 is the latest in the 4.1 series.  Could easily change to 4.1.0 instead, if that's important.

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
@jerryyin please help decide whether we use `4.1` or `4.1.1`.

**Comment by whchung** [comment]
jenkins: ok to test.

**Comment by jerryyin** [comment]
@whchung Looking at the 4.1.1 release notes I don't think it matters with either 4.1.1 or 4.1.0. From the testing stand of point it make more sense to bump to the top revision number.

**Review by jerryyin — APPROVED** [review]
LGTM

**Comment by jerryyin** [comment]
@pcf000 Please monitor dockerhub tag [here](https://hub.docker.com/repository/docker/rocm/mlir/tags?page=1&ordering=last_updated), for rocm4.1-latest. Once we have a image ready in the channel, please submit the second PR that amend the jenkinsfile.

**Pull request merged**
