### PR TITLE
Enable external CI pipeline triggers

### PR DESCRIPTION
**Pull request by jayhawk-commits**
For build triggers in public-facing CI project on Azure Pipelines: https://dev.azure.com/ROCm-CI/ROCm-CI/_build

### CODE REVIEW

**Comment by jerryyin** [comment]
My I ask where is the actual build/test defined for a rocMLIR job run? https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=1912&view=logs&j=ec508885-80b5-505f-f25e-2c1446a2d737

**Comment by jayhawk-commits** [comment]
> My I ask where is the actual build/test defined for a rocMLIR job run? https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=1912&view=logs&j=ec508885-80b5-505f-f25e-2c1446a2d737

https://github.com/ROCm/ROCm/blob/develop/.azuredevops/components/rocMLIR.yml

**Review by jerryyin — APPROVED** [review]

**Comment by krzysz00** [comment]
Ping on what still needs doing here - should we just re-kick the CI and merge once it passes?

**Comment by jayhawk-commits** [comment]
> Ping on what still needs doing here - should we just re-kick the CI and merge once it passes?

The CI has been failing even though this yaml file shouldn't affect those existing checks.

**Comment by krzysz00** [comment]
Yeah, our CI can be a touch templamental. Could you merge in `develop` and push that, see if some of the recent changes we made there resolve this?

**Pull request merged**
