### PR TITLE
Miopen dialect opt step7 : unroll loops in threadwise_copy_v2

### PR DESCRIPTION
**Pull request by whchung**
Fully unroll loops in `miopen.threadwise_copy_v2` to boost performance.

### CODE REVIEW

**Comment by whchung** [comment]
@asroy This PR is ready for review.

**Comment by whchung** [comment]
jenkins: retest this please.

**Review by asroy — APPROVED** [review]

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by whchung** [comment]
@yiqian1 we do need e2e test target on the pipeline now. After we merge #197 where all CI tests pass it seem to bring some side effects so tests for this PR can not complete now.

**Comment by whchung** [comment]
@yiqian1 I have better confidence about this PR than #197 as my local e2e tests look fine. But I'll hold off merging it after we enable some e2e tests on PR-triggered CI jobs.

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by whchung** [comment]
@yiqian1 http://ml-ci.amd.com:21096/job/MLIR/job/MLIR-downstream-unit-test/3360/consoleFull

this PR has passed selected e2e tests introduced in #218 . now I feel more confident about it.

**Pull request merged**
