### PR TITLE
[hotfix] Re-add SoftwareBF16 pass for bf16 emulation

### PR DESCRIPTION
**Pull request by sjw36**
* removed unnecessary libmlir_float16_utils runtime lib

### CODE REVIEW

**Comment by sjw36** [comment]
I will run this with nightly enabled.

**Review by jerryyin — APPROVED** [review]
LGTM but why can changes here impact accuracy?

**Review by krzysz00 — APPROVED** [review]
Can you confirm that the pass is also run on the GPU kernels - that is, that it's still in place as part of `-gpu-to-rocdl`

**Comment by sjw36** [comment]
> LGTM but why can changes here impact accuracy?

I had removed the SoftwareBF16 pass from the runner pipeline since it is not upstream. So I was getting unknown symbols so I added the mlir_float16_utils to cover, but that gave inaccurate conversion.

**Pull request merged**
