### PR TITLE
Miopen dialect opt step21 : Reinstate OptLevel to 3.

### PR DESCRIPTION
**Pull request by whchung**
After getting logic in #226 done, I reinstated OptLevel to 3 and checked with several end-to-end cases. They all seem fine now.

### CODE REVIEW

**Comment by whchung** [comment]
@yiqian1 Wondering if it's possible to trigger a nightly CI job on a particular PR? I set OptLevel to 1 some time ago to prevent incorrect compiler optimizations from happening. But it seems time to reinstate it. But I'd like a nightly CI to validate it first.

**Comment by yiqian1** [comment]
> @yiqian1 Wondering if it's possible to trigger a nightly CI job on a particular PR? I set OptLevel to 1 some time ago to prevent incorrect compiler optimizations from happening. But it seems time to reinstate it. But I'd like a nightly CI to validate it first.

I can start a new nightly CI job on a particular commit after you merge your PR into miopen-dialect. Alternatively I can start the CI using your branch that points to the commit you want to test. If your branch is used, make sure you rebase your branch with the miopen-dialect branch. Please let me know which way you'd prefer.

**Comment by whchung** [comment]
> > @yiqian1 Wondering if it's possible to trigger a nightly CI job on a particular PR? I set OptLevel to 1 some time ago to prevent incorrect compiler optimizations from happening. But it seems time to reinstate it. But I'd like a nightly CI to validate it first.
> 
> I can start a new nightly CI job on a particular commit after you merge your PR into miopen-dialect. Alternatively I can start the CI using your branch that points to the commit you want to test. If your branch is used, make sure you rebase your branch with the miopen-dialect branch. Please let me know which way you'd prefer.

Got it. Let me try merge this one , #247 , first. I'll notify you once it's in.

**Review by asroy — APPROVED** [review]

**Comment by whchung** [comment]
@yiqian1 Please help kick off a nightly CI run to validate this PR.

**Comment by yiqian1** [comment]
Non-Xdlops nightly CI has passed. 

Xdlops nightly CI has passed with one exception: mlir-miopen-driver/sanity_pv.mlir failed because of a crash related to multi-thread compilation. I've seen the same crash happened before on random tests. Since sanity_pv.mlir has passed in other CI jobs, I'm confident to say XDlops nightly CI is successful.

MIOpen-tests are still running. So far so good.

**Pull request merged**
