### PR TITLE
Vectorize LDS writeback loop in non-xdlops

### PR DESCRIPTION
**Pull request by krzysz00**
(I tested perf, it's pretty much flat, maybe a few kernels got a boost but that could be measurement error)

### CODE REVIEW

**Review by jerryyin — APPROVED** [review]
LGTM, please help keep an eye on nightly/weekly as we are close to branching.

**Review by jungpark-mlir — APPROVED** [review]
Looks good.
I was also curious about the performance and it looks the backend finally schedules and vectorizes them pretty well.

**Comment by krzysz00** [comment]
Oh, yeah, this is pretty much [NFC], by all accounts

**Comment by krzysz00** [comment]
This is now `skip-ci` until #764 gets landed

**Pull request merged**
