### PR TITLE
MIOpen dialect opt step 22 : Force index type be 32-bits wide. Take 2.

### PR DESCRIPTION
**Pull request by whchung**
The PR was reverted last week because TF e2e test was crashing. Reinstate it after sorting out TF e2e run issues.

### CODE REVIEW

**Comment by jerryyin** [comment]
@whchung Do not merge this PR even if all CI pass in MLIR end. I will use this branch to try to reproduce the TF failure we observe last Friday. I will document the entire reproducing process if this turn out to be reproducible in a different machine.

**Comment by whchung** [comment]
Will hold off merging this PR. Awaiting more info from folks testing ML frameworks.

**Comment by whchung** [comment]
@jerryyin PR#258 has passed PR-triggered CI jobs. Per discussion I'll hold off merging it after you and @rsanthanam-amd could verify things from TensorFlow side.

**Comment by whchung** [comment]
https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/182

will hold off merging this PR because at framework-level tests this PR is causing resnet50 to crash.

**Comment by whchung** [comment]
Per discussion, @jerryyin has identified the interface between MIOpen and MLIR need to be changed as well. I'm handing off this PR to @jerryyin for completing it. He will also submit relevant changes in MIOpen side as well.

**Comment by whchung** [comment]
@sunway513 now @jerryyin has become a contributor to this PR, need your approval on this one to get it merged

**Comment by sunway513** [comment]
Confirm this branch works for TF Resnet50 e2e evaluation.

**Review by sunway513 — APPROVED** [review]

**Pull request merged**
