### PR TITLE
Add support for MIGraphX to Tosa conversion

### PR DESCRIPTION
**Pull request by jungpark-mlir**
First set of operations.

https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/285

### CODE REVIEW

**Comment by whchung** [comment]
@jungpark-mlir I'm temporarily skipping CI runs for this PR before #396 gets in. Also I think this PR needs to be changed to target `miopen-dialect-llvm-update-9-21` instead `miopen-dialect`?

**Comment by jungpark-mlir** [comment]
@whchung thanks for set it to skip CI, I wasn't aware CI keep trying to build this. I suppose this needs to be merged after the llvm update because it's a part of MIGraphX integration work, not from upstream. Maybe I didn't catch up the plan around it correctly?

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by sjw36** [comment]
This looks like it needs to be rebased on miopen-dialect now that #396 has gone in.

**Comment by sjw36** [comment]
@jungpark-mlir let's go ahead and rename MIGraphX to MIXR just to shorten and not confuse with MIGraphX tool IR.

**Comment by jungpark-mlir** [comment]
Yes, that's the plan!
Just filed https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/361 
After merging the code object op support.

**Review by sjw36 — APPROVED** [review]
Looks good.

**Review by sjw36 — COMMENTED** [review]
add test

**Comment by jungpark-mlir** [comment]
Find an issue while adding a test. I'd take this chance to move conv2d rewriter from tablegen to cpp function.

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by jungpark-mlir** [comment]
Code not ready yet :(
I'll issue the retest as soon as it's ready

**Comment by jungpark-mlir** [comment]
- Added test
- Added support for non-biased convolution : converter adds a zero constant
- Fixed leftover convolution op with using cse pass -> Need to check the root cause with MLIR people and fix properly later.

**Comment by jungpark-mlir** [comment]
jenkins: retest this please.

**Comment by jungpark-mlir** [comment]
jenkins: retest this please.

**Pull request merged**
