### PR TITLE
Bump base docker to rocm 6.0

### PR DESCRIPTION
**Pull request by jerryyin**

### CODE REVIEW

**Comment by krzysz00** [comment]
Buildbot?

**Review by yiqian1 — APPROVED** [review]

**Comment by jerryyin** [comment]
@krzysz00 Nice catch!

**Comment by stefankoncarevic** [comment]
I checked now and saw that on the site https://hub.docker.com/r/rocm/mlir/tags 
There is no image with that name rocm/mlir:rocm6.0-latest
we only have rocm5.7-latest
When I changed Jenkins to use that image as well I got this error:
docker pull rocm/mlir:rocm6.0-latest
Error response from daemon: manifest for rocm/mlir:rocm6.0-latest not found: manifest unknown: manifest unknown

**Comment by jerryyin** [comment]
@stefankoncarevic That image will only be built after this PR is merged. 

Check out here: https://github.com/ROCm/rocMLIR/blob/cccbac3ce636f611079b48e18da83f5ed0d93dfe/mlir/utils/jenkins/build-dockerfile.sh#L73-L78

I'm going to merge the PR now. Take a second look after ~10 mins and the image should be ready to go.

**Pull request merged**
