### PR TITLE
Clean up temporary steps from #315 and remove old Jenkinsfiles

### PR DESCRIPTION
**Pull request by krzysz00**

### CODE REVIEW

**Review by jerryyin — APPROVED** [review]
Good work, thanks for spending all the effort and go the extra step to come up with the much more maintainable version of a Jenkinsfile!

//CC @whchung

**Review by parallelo — APPROVED** [review]
Mods LGTM.  

To avoid temporary nightly CI failures, it seems the follow-up question is:  how often are docker images updated for this project?

**Comment by jerryyin** [comment]
@parallelo We do docker updates quietly rarely. The policy is that when things get updated for the dockerfile, it is up to the developer who make the change that it will never break. Most typically the update in dockerfile should happen in its standalone PR. I'm giving the approval in consideration that the python dependencies are  used in nightly test only and that docker image update usually come in less than 30 mins. But otherwise this is nice catch. 

I'd ask @krzysz00 to merge the PR early enough so that the docker job has enough time to pick up and push a newer version of docker image so nightly test doesn't fail out of our old docker images.

**Comment by krzysz00** [comment]
@jerryyin I was going to manually run the Docker job now

**Comment by krzysz00** [comment]
And it looks like we run those on push now, http://ml-ci.amd.com:21096/job/MLIR/job/rocm-docker/lastBuild/pollingLog/

**Comment by jerryyin** [comment]
@krzysz00 Correct. Looks like the updated image is already in our channel, we are good.

**Pull request merged**
