### PR TITLE
MLIR#185: convert all loops to affine.for in MIOpen lowering

### PR DESCRIPTION
**Pull request by sjw36**
Addresses https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/185

### CODE REVIEW

**Review by whchung — CHANGES_REQUESTED** [review]
@sjw36 I can understand the change introduced in this PR, but I don't get the big picture yet.

Could you illustrate how element-wise fusion be carried out after this PR? For example, say a conv is followed by a bias, how would the bias logic be fused? Or if we have a non-trivial computation constructed also using `affine` dialect, how would it be stitched with existing algorithm?

I guess it should be right after the tail of the loop where we do the final `blockwise_gemm`?

**Comment by sjw36** [comment]
Initially I see the fusion happening on the threadwise_copy loops writing the output tensor. Here is some pseudo-code (there are many more issues to resolve, especially the coordinate calculations for OOB).

 ```
   affine.for %72 = %c0 to %c1 {
      affine.for %73 = %c0 to %c2 {
        affine.for %74 = %c0 to %c4 {
          affine.for %75 = %c0 to %c2 {
            affine.for %arg8 = %c0 to %c4 {
              %81 = load %oregs[%73, %74, %75] : memref<1x8x8xf32, 5>
              store %81, %3[%coords] : <output type>
            }
          }
        }
      }
    }
```

Any following operations (such as bias add or activation) would need to have aligned affine.for loops which read the same coords of the output tensor and perform some operation on it before writing it back out. 

 ```
   affine.for %72 = %c0 to %c1 {
      affine.for %73 = %c0 to %c2 {
        affine.for %74 = %c0 to %c4 {
          affine.for %75 = %c0 to %c2 {
            affine.for %arg8 = %c0 to %c4 {
              %91 = load %3[%coords] : memref<output type>
              %92 = load %bias[%coords] : memref<output type>
              %93 = addf %91, %92
              store %93, %3[%coords] : <output type>
            }
          }
        }
      }
    }
```

These loops fused would look like:

 ```
   affine.for %72 = %c0 to %c1 {
      affine.for %73 = %c0 to %c2 {
        affine.for %74 = %c0 to %c4 {
          affine.for %75 = %c0 to %c2 {
            %75 = index_cast %arg7 : index to i32
            affine.for %arg8 = %c0 to %c4 {
              %81 = load %oregs[%73, %74, %75] : memref<1x8x8xf32, 5>
              store %81, %3[%coords] : <output type>
              %91 = load %3[%coords] : memref<output type>
              %92 = load %bias[%coords] : memref<output type>
              %93 = addf %91, %92
              store %93, %3[%coords] : <output type>
            }
          }
        }
      }
    }
```

Once fused the Read-after-Write should be optimized away.

 ```
   affine.for %72 = %c0 to %c1 {
      affine.for %73 = %c0 to %c2 {
        affine.for %74 = %c0 to %c4 {
          affine.for %75 = %c0 to %c2 {
            %75 = index_cast %arg7 : index to i32
            affine.for %arg8 = %c0 to %c4 {
              %81 = load %oregs[%73, %74, %75] : memref<1x8x8xf32, 5>
              %92 = load %bias[%coords] : memref<output type>
              %93 = addf %81, %92
              store %93, %3[%coords] : <output type>
            }
          }
        }
      }
    }
```

**Comment by whchung** [comment]
> Initially I see the fusion happening on the threadwise_copy loops writing the output tensor. Here is some pseudo-code (there are many more issues to resolve, especially the coordinate calculations for OOB).

But in this PR, `miopen.threadwise_copy` is not changed at all?

Back to my earlier comment, I guess the place to inject the fused element-wise operations, should be right after the tail of the loop where we do the final `blockwise_gemm`, and right before the final `threadwise_copy` or unroll loop of `threadwise_copy_v2`?

**Comment by sjw36** [comment]
> > Initially I see the fusion happening on the threadwise_copy loops writing the output tensor. Here is some pseudo-code (there are many more issues to resolve, especially the coordinate calculations for OOB).
> 
> But in this PR, `miopen.threadwise_copy` is not changed at all?
> 
> Back to my earlier comment, I guess the place to inject the fused element-wise operations, should be right after the tail of the loop where we do the final `blockwise_gemm`, and right before the final `threadwise_copy` or unroll loop of `threadwise_copy_v2`?

Yes, I was out-of-date. I see the changes on May 20 that unrolled the threadwise_copy. This may be pointless as we would not have any loops to fuse (except subsequent element-wise ops). It would be easier to inject the subsequent ops in between the gemm and copy but I was looking for a more general solution.

This PR may have value in other fusion cases such as horizontal fusion. Should we go with affine anyway?

**Comment by whchung** [comment]
> This PR may have value in other fusion cases such as horizontal fusion. Should we go with affine anyway?

I agree it's fine to use affine dialect in places introduced in this PR. I'll approve this PR now that we are on the same page.

**Review by whchung — APPROVED** [review]

**Comment by whchung** [comment]
@sjw36 I'll hold off taking this PR after we get an end-to-end full convergence run of resnet50 from TensorFlow from @sunway513 's team.

**Pull request merged**
