### PR TITLE
Move to rocm 4.3 part 2 (Update Jenkinsfiles)

### PR DESCRIPTION
**Pull request by krzysz00**

### CODE REVIEW

**Review by yiqian1 — APPROVED** [review]

**Comment by whchung** [comment]
Will hold off this one along with #415.

**Comment by whchung** [comment]
Want a second pair of eyes from @jerryyin . Now since #415 has been merged, I'm removing `skip-ci` label for this PR now.

**Comment by jerryyin** [comment]
ROCm 4.3 image is available now, [here](https://hub.docker.com/layers/rocm/mlir/rocm4.3-latest/images/sha256-5b119875518cbd9213bd9979d68916315ef08fddb89ad05eb0a759212e1e8e49?context=repo). Please resolve conflict and trigger a CI run @krzysz00

**Comment by sjw36** [comment]
@krzysz00 looks like CI was never run on this. Please revert until it gets a clean run. Nevermind, I see the run but it is causing failures in nightly.

**Comment by krzysz00** [comment]
Are we seeing issues?

**Comment by sjw36** [comment]
yes, see https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/371

**Comment by sjw36** [comment]
I think a change this big should have run full nightly testing to validate.

**Comment by sjw36** [comment]
@krzysz00 please revert it until a full nightly run passes.

**Comment by whchung** [comment]
@sjw36 Instead of reverting, I'll force push to go back one commit.

**Pull request merged**
