### PR TITLE
[hotfix] fixed test with merge conflict

### PR DESCRIPTION
**Pull request by sjw36**

### CODE REVIEW

**Comment by sjw36** [comment]
This somehow got merged into TOT.

**Review by krzysz00 — CHANGES_REQUESTED** [review]
Could you instead regenerate the Resnext101 tests?

That's 
```
python3 ./mlir/utils/generateE2ETest.py -d .  -i ./mlir/utils/Resnext101Config.toml
```

**Comment by sjw36** [comment]
> 

Did that, no change..

**Review by krzysz00 — APPROVED** [review]
Given that this gets us to the state of the test file if one were to auto-generate it, approved, and I'm willing to give it a CI override too

**Comment by sjw36** [comment]
sure, let's skip CI since it doesn't seem to run this test anyway.

**Pull request merged**
