### PR TITLE
Update Jenkinsfiles to ROCm 4.1.

### PR DESCRIPTION
**Pull request by pcf000**
Someday I'll figure out which paths send immediately and which don't.

Update the five Jenkinsfiles to use ROCm 4.1.1 and the associated docker image.  The .downstream, .nightly, and .perf files have all been tested on a private Jenkins job that is essentially check-mlir.  The .perf-gfx908 file wants a "test-0" Jenkins label that apparently doesn't exist now.  The .upstream file explicitly fetches the llvm-project repo even though it's operating within the llvm-project-mlir repo, and fails to set up directories.

The tangled commits come from trying to make the .upstream file work, and messing up the merges and pushes.  Sorry.

### CODE REVIEW

**Comment by whchung** [comment]
@pcf000 you can try squash all commits in your local branch.

**Comment by whchung** [comment]
We'll squash the commits when we merge the PR so it's fine to have a relatively messy timeline. But it's still a good idea to tidy it up.

**Comment by pcf000** [comment]
To try to fix the .upstream file, I had to push my commits, because Jenkins is fetching the files from the repo.  Having pushed, I can't easily squash.  Meanwhile, other commits happened in the main repo, which caused merge commits in mine.  Then I tried to clean it up by making a new branch from miopen-dialect, but somehow that just duplicated the merges I tried to circumvent.  I need to enhance my techniques for the future.

**Comment by jerryyin** [comment]
@pcf000 What you can do is to start a branch from the latest of `miopen-dialect`. Then cherry-pick all the necessary commits from this branch, submit a new PR. (Or you can use the same branch name, but do a force push. It will update this PR instead of the need to open a new one)

We don't do any merge commits in this repo, so it'd be a good practice.

**Comment by pcf000** [comment]
Thanks.  And the reason for the second pull request is that my old company's review tool wasn't coupled with the commit sequence;  I made a second review for the second set of changes by habit.  I didn't realise that it would effectively supersede the first one, but now I know.  Getting my mistakes out of the way early, I guess.

**Pull request closed without merging**
