### PR TITLE
Enable KPACK for backward weight convolution.

### PR DESCRIPTION
**Pull request by whchung**
This PR enables KPACK for backward weight convolution when XDLOPS it used.

Combined with #548, the speed of backward weight convolution would be greatly improved.

Benchmark commmand:
```
./bin/miopen-gen --x2 --operation conv2d_bwd_weight -t f16 --batchsize 64 --in_channels 1024 --out_channels 1024 --in_h 14 --in_w 14 --out_h 14 --out_w 14 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 --groupsize 1 -ph | ./bin/mlir-miopen-driver -c | rocprof --stats ./bin/mlir-rocm-runner --shared-libs=./lib/librocm-runtime-wrappers.so,./external/llvm-project/llvm/lib/libmlir_runner_utils.so --entry-point-result=void
```

This is a backward weight convolution which uses XDLOPS, in fp16, no padding along Gemm M/N/K. Therefore a 0-init kernel and a conversion kernel will be used.

At tip of `miopen-dialect`:
```
# cat results.stats.csv
"Name","Calls","TotalDurationNs","AverageNs","Percentage"
"miopen_conv2d_bwd_weight_gkcyx_ngchw_ngkhw_0.kd",1,290640047,290640047,51.83518016940135
"miopen_conv2d_bwd_weight_gkcyx_ngchw_ngkhw_2.kd",1,264794271,264794271,47.2256280123375
"miopen_conv2d_bwd_weight_gkcyx_ngchw_ngkhw_1.kd",1,5266052,5266052,0.9391918182611508
```
Total time: `560700370`

With PR #548:
```
# cat results.stats.csv
"Name","Calls","TotalDurationNs","AverageNs","Percentage"
"miopen_conv2d_bwd_weight_gkcyx_ngchw_ngkhw_1.kd",1,5289100,5289100,99.4823779017496
"miopen_conv2d_bwd_weight_gkcyx_ngchw_ngkhw_2.kd",1,20960,20960,0.3942354352953568
"miopen_conv2d_bwd_weight_gkcyx_ngchw_ngkhw_0.kd",1,6560,6560,0.12338666295503534
```
Total time: `5316620`

With PR #548 + this PR:
```
# cat results.stats.csv
"Name","Calls","TotalDurationNs","AverageNs","Percentage"
"miopen_conv2d_bwd_weight_gkcyx_ngchw_ngkhw_1.kd",1,1035033,1035033,97.36602720705754
"miopen_conv2d_bwd_weight_gkcyx_ngchw_ngkhw_2.kd",1,20640,20640,1.9416142302261548
"miopen_conv2d_bwd_weight_gkcyx_ngchw_ngkhw_0.kd",1,7360,7360,0.6923585627163032
```
Total time: `1063033`. 5X the improvement than #548 . 527X than `miopen-dialect`.

### CODE REVIEW

**Comment by whchung** [comment]
@jerryyin CI fails at `Test selected MIOpen configs` stage. But strangely speaking the very same test command would pass when I run it locally. I'll check with you off-line.

**Review by krzysz00 — APPROVED** [review]
I have no complaints about the code, and, assuming it has passed tests, let's send it in.

**Comment by whchung** [comment]
It seems this PR uncovers a previously unknown race condition inside MIOpen. I'm still digging into it.

The tuning loop could complete without any issue if we force MIOpen to run with just 1 thread using an environment variable. On the other hand, with the default multi-threaded setting, MIOpen would somehow fail to obtain the GCN code object produced by MLIR.

It's quite bizarre that the race condition is uncovered here. We are only tweaking the internals of the lowering pipeline in this PR, and change nothing about integration logic with MIOpen.

**Comment by whchung** [comment]
Turns out there are multiple issues behind:
- The potential race condition turns out to be that the tuning search space in MIOpen solver would be strangely modified between a single-threaded environment v multi-threaded environment. It's not in the scope of this PR, so I logged as a ticket at: https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1472
- Forgot to reject some invalid tuning parameters with KPACK on: fixed in #4867aac .
- The default perfDB used in CI would yield higher-than-desired errors for certain configs. After tuning, those errors would be gone for those particular configs. This suggest a full re-tuning is needed.
- On the other hand, after a full re-tuning with the default search space in MIOpen MLIR solver, in 1 particular config of resnet50, the fastest kernel after tuning would yield higher-than-desired errors.
- After investigation, the default tuning search space in MIOpen MLIR solver always assume KPACK = 4 or 8, but for that particular config, the fastest + correct kernel is actually in KPACK = 1 or 2 (the two are very close in performance). Therefore, the default tuning search space in MIOpen MLIR solver needs to be changed.
- Running a full tuning cycle on resnet50 configs after enlarging the default tuning search space to ensure no other surprises.
- With modified tuning search space, all resnet50 configs in fp32 / fp16 data type can pass in all directions, and now quite a few configs on forward and backward weight can leverage KPACK=2 in fp32, which was previously not used.

Next steps to get it merged, along with necessary changes to MIOpen:

- verify tuning can go through with my branches in MLIR + MIOpen on both fp32/fp16 : done.
- change jenkinsfile on the MLIR branch to point to the MIOpen branch with the revised tuning search space : done.
- run MLIR weekly on the MLIR branch to get a new perfdb for this PR to use. http://rocmhead.amd.com:8080/job/MLIR/job/mlir-weekly/configure . Weekly run: http://rocmhead.amd.com:8080/blue/organizations/jenkins/MLIR%2Fmlir-weekly/detail/mlir-weekly/36/pipeline
  - weekly CI resulted in 3 failures (fastest kernel which generates incorrect answers). the issues are not seen locally. from the logs it seems the tuning search space on the weekly CI is still different from local environment. comparing logs, and jenkins set up.

- run CI on this PR again, using the new perfdb.
- submit an MIOpen PR for the revised tuning search space : https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1474

**Comment by whchung** [comment]
PR-triggered CI has passed. But we shall NOT merge it right now until we get a full passing weekly CI run. Working on that right now.

**Comment by whchung** [comment]
Merging this PR after we finally getting a passing weekly CI.
http://10.236.106.97:8080/blue/organizations/jenkins/MLIR%2Fmlir-weekly/detail/mlir-weekly/41/pipeline

**Pull request merged**
