### PR TITLE
[DO NOT SQUASH] Upstream merge August'24

### PR DESCRIPTION
**Pull request by manupak**
closes : https://github.com/ROCm/rocMLIR-internal/issues/1572

### CODE REVIEW

**Comment by krzysz00** [comment]
Notes: 
- We still seem to be carrying an LLVM patch at `llvm/lib/Target/AMDGPU/GCNHazardRecogni` - do we know the history on that?
- @pcf000 could you get PRs filed upstream with the FP8-related changes you made?
- @djramic  What's the status of getting `amdgpu.dpp` merged?

**Comment by krzysz00** [comment]
(On that note, how's `sched_barrier` doing upstream?)

**Comment by manupak** [comment]
> We still seem to be carrying an LLVM patch at llvm/lib/Target/AMDGPU/GCNHazardRecogni - do we know the history on that?

I'd ping @giuseros as these are from gfx12.

 > (On that note, how's sched_barrier doing upstream?)

 well its not reverted if thats what you are asking : https://github.com/llvm/llvm-project/blob/db8ef6188cbbe2125e6d60bdef77a535105772df/mlir/include/mlir/Dialect/AMDGPU/IR/AMDGPU.td#L428
 
 but its not in amd-staging : https://github.com/ROCm/llvm-project/blob/amd-staging/mlir/include/mlir/Dialect/AMDGPU/IR/AMDGPU.td

**Comment by djramic** [comment]
> * @djramic  What's the status of getting `amdgpu.dpp` merged?

I think @stefankoncarevic has a PR for amdgpu.dpp

**Review by krzysz00 — APPROVED** [review]
Having investigated the post-merge diffs, I see no changes that concern me, approved

**Pull request merged**
