### PR TITLE
Add sanity tests for -pv .

### PR DESCRIPTION
**Pull request by whchung**
Add one sanity test to check -pv always produces valid MLIR for all possible data types and lowering paths.

### CODE REVIEW

**Comment by whchung** [comment]
This PR depends on #76 be merged first.

**Review by asleepzzz — COMMENTED** [review]
looks good to me

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by whchung** [comment]
@asleepzzz ping.

**Review by asleepzzz — COMMENTED** [review]
these tests can cover

**Review by asleepzzz — APPROVED** [review]
these tests can cover

**Pull request merged**
