### PR TITLE
Revert "Re-enable backward weight with atomic add f32"

### PR DESCRIPTION
**Pull request by jerryyin**
Reverts ROCmSoftwarePlatform/llvm-project-mlir#310

### Following record has been failing: 

 - http://rocmhead:8080/blue/organizations/jenkins/xdlops-miopen-dialect-outoftree-subtree-4/detail/xdlops-miopen-dialect-outoftree-subtree-4/1/pipeline/1153
 - http://rocmhead:8080/job/mlir-nightly-all/36/console
 - http://rocmhead:8080/job/mlir-nightly-all/30/console

Please search for "failed" in the log.

### Following record before this PR submitted has been passing:
 - http://rocmhead:8080/job/mlir-nightly-all/25/console

### Additional failing cases

> ./llvm/bin/mlir-miopen-driver --x2 --operation conv2d_bwd_weight --groupsize 1 --batchsize 256 --in_channels 1024 --out_channels 2048 --in_h 14 --in_w 14 --out_h 7 --out_w 7 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 2
--conv_stride_w 2 --padding_h 0 --padding_w 0 -pv --rand_type float --rand 123 -c | ./llvm/bin/mlir-rocm-runner --shared-libs=./llvm/lib/librocm-runtime-wrappers.so,./llvm/lib/libmlir_runner_utils.so --entry-point-result=void
Unranked Memref base@ = 0x7ffe37da7330 rank = 1 offset = 0 sizes = [1] strides = [1] data =
[0]

> ./llvm/bin/mlir-miopen-driver --x2 --operation conv2d_bwd_weight --groupsize 1 --batchsize 256 --in_channels 512 --out_channels 128 --in_h 28 --in_w 28 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 -pv --rand_type float --rand 123 -c | ./llvm/bin/mlir-rocm-runner --shared-libs=./llvm/lib/librocm-runtime-wrappers.so,./llvm/lib/libmlir_runner_utils.so --entry-point-result=void
Unranked Memref base@ = 0x7ffe79dc0d70 rank = 1 offset = 0 sizes = [1] strides = [1] data =
[0]

> ./llvm/bin/mlir-miopen-driver --x2 --operation conv2d_bwd_weight --groupsize 1 --batchsize 256 --in_channels 512 --out_channels 128 --in_h 28 --in_w 28 --fil_h 1 --fil_w 1 --dilation_h 1 --dilation_w 1 --conv_stride_h 1 --conv_stride_w 1 --padding_h 0 --padding_w 0 -pv --rand_type float --rand 123 -c | ./llvm/bin/mlir-rocm-runner --shared-libs=./llvm/lib/librocm-runtime-wrappers.so,./llvm/lib/libmlir_runner_utils.so --entry-point-result=void
Unranked Memref base@ = 0x7ffe79dc0d70 rank = 1 offset = 0 sizes = [1] strides = [1] data =
[0]

### CODE REVIEW

**Comment by whchung** [comment]
@jerryyin #310 was merged because we have a full passing CI log:

http://10.236.106.97:8080/job/test-PR310/6/console

Could you help discern any discrepancies between that passing run versus what you're seeing?

**Comment by whchung** [comment]
I will hold off taking this PR until we truly figure out what's going on when MIOpen launches MLIR on backward weight configs.

**Comment by whchung** [comment]
Based on the current investigation so far it seems `-pv` might have trouble working with `--conv_config` . Awaiting updates from @yiqian1 .

**Comment by jerryyin** [comment]
Short summary here on the investigation we have: 
- MIOpen and MLIR use different logic to check for validity of a convolution, but both may be too strict for the wrw convolution we have.
  - This is exacerbate that problem we are are not tuned, and precision can be impacted by use of tuning parameters.
- Wrw convolution numeric precision has been a very controversial topic in MIOpen as well.
- This on-going investigation should not block either CI or out-of-tree transition

 
TODO items:

In MLIR

- We need to adjust the precision threshold in our tests, based on direction of convolution
- We need to adopt minimal amount of float point validation for sanity check
- We will continue to test MIOpenDriver test, but temporarily ignore the test results in wrw direction
	
In MIOpen
- @ltqin needs to follow up with the wrw precision to make sure this does not block MLIR/MIOpen integration

Based on the above, closing the ticket now.

**Comment by whchung** [comment]
@jerryyin I checked with @ltqin , it seems you haven't passed these findings with him yet?

**Comment by jerryyin** [comment]
@whchung It's all documented here + [this MIOpen ticket](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1085#issuecomment-897315009), and both place @ltqin was assigned so he should see. Besides, it is not until this morning that I see @shaojiewang's message did I think this again point back to the kernel implementation. Reopening this PR because all my findings are on top of the PR description (and use this as the media for discussion/notification). I do expect @ltqin to also respond in either the ticket or this PR, otherwise with existing evidence I'm leaning towards reverting it.

----

Meanwhile I pinged @ltqin a second ago.

**Comment by ltqin** [comment]
@jerryyin  I will check the configs. and If floating-point numbers are used, they cannot be completely equal. They should be within a range, such as less than 0.00000 1

**Comment by jerryyin** [comment]
@ltqin Understood. I have left you some additional comments regarding on how to dump and compare cpu/gpu result in teams. At the time when we measure it, the largest fp gap is around 0.002. And there are quite prevalent numeric gaps compared to cpu. Since MIOpen use RMS to calculate the end result, all difference accumulated may make it too large. (You probably still need to follow up with MIOpen to make sure because our fp validation use a different way than MIOpen, we use per elelment wise comparison to be less than 1e-7. And if you think 1e-7 is too much, we should amend it to a more realistic range).

But I think you have a good control group here: Before this PR, the numerical precision is good by both MLIR and MIOpen. You may use the dumped gpu result before this PR to figure what's the accepted precision like.

**Comment by ltqin** [comment]
@jerryyin I got the same result  in MLIR miopen. Next, I will test it with miopen-driver

**Comment by ltqin** [comment]
@jerryyin All the results you got have been reproduced, and I'm looking for the reason.
I would now like to confirm some questions:
(1) Whether to clear Wei data in miopen-driver(set zero to wei data)?
(2) Can the random number be set between 0 and 0.01 in the mlir-miopen-driver? just like miopen-driver

**Comment by yiqian1** [comment]
> (2) Can the random number be set between 0 and 0.01 in the mlir-miopen-driver? just like miopen-driver

No, mlir-miopen-driver uses random float data between -1 and 1.

**Comment by yiqian1** [comment]
> Based on the current investigation so far it seems `-pv` might have trouble working with `--conv_config` . Awaiting updates from @yiqian1 .

The problems with '--conv_config' have been fixed.

**Comment by jerryyin** [comment]
@ltqin 

> (1) Whether to clear Wei data in miopen-driver(set zero to wei data)?

No it is not cleared to zero before and I just validated that clearing weight data to zero help fixed the validation issue on MIOpen side. The question I have is:
 - Is it right that we should always set weight tensor to zero under all circumstances? Any optimization case where we can avoid this additional operation?
 - Why is this not required before your PR and required after we introduced atomic add?

> (2) Can the random number be set between 0 and 0.01 in the mlir-miopen-driver? just like miopen-driver

Per @yiqian1 this is not possible now, but will it be useful if we run into similar kind of issue again?

**Comment by ltqin** [comment]
> @ltqin
> No it is not cleared to zero before and I just validated that clearing weight data to zero help fixed the validation issue on MIOpen side. The question I have is:
> 
> * Is it right that we should always set weight tensor to zero under all circumstances? Any optimization case where we can avoid this additional operation?

if using atomic add, “output” must set to zero
> * Why is this not required before your PR and required after we introduced atomic add?
> 
In mlir-miopen-driver, already set zero to wei in "main" function

**Comment by jerryyin** [comment]
Closing the PR with all known issues fixed, or tracked in other PRs:
 - https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1104
 - https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/pull/339

**Pull request closed without merging**
