### PR TITLE
[DO NOT SQUASH] Move fusion fixup rewrites to their own pass + #742

### PR DESCRIPTION
**Pull request by krzysz00**
These patterns shouldn't be in conv-to-gemm, both because they'll be
applicable to a GEMM by itself and because they're only used when
fusion is enabled.

### CODE REVIEW

**Comment by krzysz00** [comment]
@sjw36 @jungpark-mlir Can I get this poked along so the GEMM operator can land?

**Comment by jungpark-mlir** [comment]
> @sjw36 @jungpark-mlir Can I get this poked along so the GEMM operator can land?

I'm fine with that

**Comment by krzysz00** [comment]
@jungpark-mlir To rephrase, the only actual change in this PR is the fusion-fixup pass. That still needs review (although the only objections I can see is naming or a broad opposition to moving those rewrites to their own pass). The GEMM operator got merged in here because it depended on this PR and got approved first.

**Review by jungpark-mlir — COMMENTED** [review]
Actually let's try to find another name for the pass.
miopen-fold-to-transform
miopen-fold-transpose

**Comment by krzysz00** [comment]
The question is, and this is an @sjw36 question since he's working on some fusion stuff, do we see this pass either gaining more patterns or being removed? If so, we might want to keep the current name because it'll either become relevant or because it'll be deleted

**Review by sjw36 — APPROVED** [review]
Approved once you change the name (as per @jungpark-mlir 's comment).

**Comment by krzysz00** [comment]
Thanks for the suggested names, `-miopen-fold-transpose` will be landing soon

**Pull request merged**
