### PR TITLE
GitHub status

### PR DESCRIPTION
**Pull request by okakarpa**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
@okakarpa please rebase . There are too many unrelated commits in this PR

**Comment by whchung** [comment]
Also, please supply a description to this PR as it seems to affect quite large over how we do e2e tests.

**Comment by okakarpa** [comment]
> Also, please supply a description to this PR as it seems to affect quite large over how we do e2e tests.

Please ignore this pr for now i am working on status status notifications tests for the pr  that is the reason i didn't add any reviewers yet. will rebase in next version.

**Pull request closed without merging**
