### PR TITLE
Re-enable backward weight with atomic add f32

### PR DESCRIPTION
**Pull request by ltqin**
This PR re-enabled backward weight with atomic add for all valid configs except those that need padding gemmK , gemmN or gemmM. Those configs  need extra investigation and will be covered in another PR

### CODE REVIEW

**Review by whchung — CHANGES_REQUESTED** [review]
@ltqin I didn't see anything being specified in the description of this PR.

Please help provide evidence that you have verified all tests in the nightly CI can pass with this PR. You can work with @yiqian1 or @krzysz00 to set up a nightly CI test specifically for this PR.

**Comment by whchung** [comment]
@ltqin Please revise the title. Revert-revert is an eyesore to me.

**Comment by yiqian1** [comment]
The XDLops CI job for this PR has passed. http://10.236.106.97:8080/job/test-PR310/6/console

**Comment by ltqin** [comment]
ci test pass:
http://10.236.106.97:8080/job/test-PR310/6/console

**Review by whchung — APPROVED** [review]
I was out sick in the past couple of days. LGTM.

**Pull request merged**
