### PR TITLE
Add the migraphx integration script as a jenkins pipeline

### PR DESCRIPTION
**Pull request by giuseros**
Fixes: https://github.com/ROCmSoftwarePlatform/rocMLIR-internal/issues/1172

### CODE REVIEW

**Comment by giuseros** [comment]
@manupak @jerryyin @yiqian1  how do I test this?

**Comment by jerryyin** [comment]
@giuseros You can create a new job that tracks in particular this jenkins file.

You can probably ignore the PR CI for this one because it will not exercise anything meaningful.

**Comment by giuseros** [comment]
I gave it a try, but my understanding is that I need to have the branch in this repo. When I try to push mine here I receive this error:
```
$ git push -u origin issue1172
ERROR: The `ROCmSoftwarePlatform' organization has enabled or enforced SAML SSO. To access
this repository, you must use the HTTPS remote with a personal access token
or SSH with an SSH key and passphrase
that has been authorized for this organization. Visit
https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/ for more information.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Is there any authorization I require to push branches in this repo?

**Comment by giuseros** [comment]
Closing in favour of https://github.com/ROCmSoftwarePlatform/rocMLIR/pull/1277

**Pull request closed without merging**
