### PR TITLE
Create file listing the renset50 configs as arguments to MIOpen

### PR DESCRIPTION
**Pull request by krzysz00**
The resnet50 configs are needed in multiple validation and performance
tests. To reduce duplicaiton, factor them out into a file.

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by krzysz00** [comment]
@yiqian1 - here's the file you wanted. The 23rd config was commented out with a FIXME though - what's that about?

**Comment by whchung** [comment]
`-c 3` that config isn't fully supported yet, #188 solves part of it, but only in forward direction.

**Review by yiqian1 — APPROVED** [review]

**Comment by whchung** [comment]
jenkins: ok to test.

**Pull request merged**
