### PR TITLE
Add MIGraphX erf op and its lowering

### PR DESCRIPTION
**Pull request by manupak**
This commit adds migraphx.erf op and its
lowering to tosa.erf with tests.

closes : https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/867

### CODE REVIEW

**Review by krzysz00 — COMMENTED** [review]
The MIGraphX part of this looks perfectly fine to me.

**Comment by manupak** [comment]
Rebased now. -- now only has MIGraphX things here.

**Review by krzysz00 — APPROVED** [review]
Approved, but do we perhaps want to restrict this to f32 tensors because we don't have lower-precision erf?

**Comment by krzysz00** [comment]
(Or, more generally, do we want to fix up gpu-to-rocdl to handle input types not supported by the functions by way of some extf's)

**Comment by manupak** [comment]
We do have it tested here for f16 too, but do u mean like fp8?

**Comment by manupak** [comment]
> Approved, but do we perhaps want to restrict this to f32 tensors because we don't have lower-precision erf?

We have it for f16 too.

**Comment by krzysz00** [comment]
Ah. In which case, assuming we have a lowering pattern for f16, never mind all that

**Comment by manupak** [comment]
No worries

**Comment by manupak** [comment]
Thanks!

**Pull request merged**
