### PR TITLE
MLIR#125: Change kernel naming to be fully user controlled

### PR DESCRIPTION
**Pull request by sjw36**
* use --kernel_name exactly
* error if it is not unique

### CODE REVIEW

**Comment by sjw36** [comment]
Addresses issues with naming in https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/125

**Review by jerryyin — COMMENTED** [review]
Overall LGTM.

But is it possible to unify the kernel naming logic such that between `mlir-miopen-driver` and `libMLIRMIOpen` both:
 - If no kernel name get assigned, give it a \<kernel-base-name\>_\<kernel-id\>
 - if kernel name is assigned, use the assigned name

This is just so that we get exact similar executable when we do debugging, for example.

**Comment by sjw36** [comment]
Let me see. It is challenging since the driver will instantiate all kernels in the same module but the library will only create 1 kernel per module.

**Review by jerryyin — APPROVED** [review]

**Comment by jerryyin** [comment]
> driver will instantiate all kernels in the same module but the library will only create 1 kernel per module.

True, I didn't think of that when leaving the comment. It seems to be more work for a trivial feature necessary.

**Pull request merged**
