### PR TITLE
MLIR#283: update llvm (9/21/21)

### PR DESCRIPTION
**Pull request by sjw36**
Changes in mlir (miopen):

* many similar std and dialect ops consolidated into memref dialect (alloc/dealloc/load/store/cast/reshape/subview/etc)
* moved math::<utility_funcs> to math_util namespace
* changed tosa-to-miopen to use memref.expand_shape
* minor refactor of RewritePatterns
* Much of BackendUtils is superceded by SerializeToHsaco
* updated tools for new SerializeToHsaco
* alot of test updates for memref dialect
* gpu-to-rocdl now requires gpu.func (vs func)

Changes in LLVM subtree:

* cleanup printers for miopen specific ops
* fixed SerializeToHsaco for target triple, chip, features
* Added back vector.tuple and vector.tuple_get impls
* Added mlir::registerToROCDLIRTranslation for -mlir-to-rocdlir

### CODE REVIEW

**Comment by sjw36** [comment]
@whchung @jerryyin @krzysz00 this should be up to date on our tree. Please hold off on merging other PRs. Thanks

**Comment by sjw36** [comment]
FINALLY!!! PR testing completed and passed. (I accidentally re-ran it, hope it passes as well)

Please review so we can push this. Thanks.

**Review by whchung — APPROVED** [review]
@sjw36 Thanks for pulling this off.

It seems the only thing we retained using obsolete logic in upstream is vector.tuple and vector.tuple_get, right?

**Comment by sjw36** [comment]
Unfortunately the tests are hanging again. It seems to be a limitation in the system that only allows up to 20 Gb memory. When I run locally these hanging tests use up to 36 Gb.

**Comment by sjw36** [comment]
Changing from llvm::SmallVector to std::array improved runtime by 3x. I don't believe there actually were memory issues, probably just node issues on prj47-rack-05. Omkar pushed this to another node.

**Comment by sjw36** [comment]
Here is the 'perf' report with llvm::SmallVector:

 ```
# Overhead  Command          Shared Object                              Symbol
 # ........  ...............  .........................................  ..................................................................................
 #
     40.93%  mlir-rocm-runne  librocm-runtime-wrappers.so.VERSION        [.] mcpuConv2d
     27.23%  mlir-rocm-runne  librocm-runtime-wrappers.so.VERSION        [.] llvm::SmallVectorTemplateCommon<long, oid>::operator[]
     20.12%  mlir-rocm-runne  librocm-runtime-wrappers.so.VERSION        [.] llvm::SmallVectorBase<unsigned int>::size
     10.83%  mlir-rocm-runne  librocm-runtime-wrappers.so.VERSION        [.] llvm::SmallVectorTemplateCommon<long, oid>::begin
      0.03%  mlir-rocm-runne  libLLVMCodeGen.so.14git                    [.] llvm::MCRegisterInfo::DiffListIterator::isValid
      0.02%  mlir-rocm-runne  libLLVMCodeGen.so.14git                    [.] llvm::SparseMultiSet<llvm::PhysRegSUOper, llvm::identity<unsigned int>, unsign
      0.01%  mlir-rocm-runne  libLLVMCodeGen.so.14git                    [.] llvm::SparseMultiSet<llvm::PhysRegSUOper, llvm::identity<unsigned int>, unsign
      0.01%  mlir-rocm-runne  libLLVMCodeGen.so.14git                    [.] llvm::MCRegisterInfo::DiffListIterator::advance
      ...
```

**Comment by krzysz00** [comment]
Makes sense, since these are actually arrays known to have _exactly_ 5 elements.

We should probably look for more of these places where we store dimensions and convert them over.

Though for abstraction cleanness, I'd make the type something like `convDims`, which will be a `std::array<5>` now, and then an `std::array<6>` when we start to allow 3D, for example.

**Comment by whchung** [comment]
@sjw36 could we restart the CI run and kill all others pending jobs so this one gets the highest priority? I believe more and more subsequent PRs now hinge on this one getting merged.

**Comment by sjw36** [comment]
I am working with @okakarpa to get this through.. currently all gfx908 nodes are busy..

**Comment by sjw36** [comment]
This PR had several commits so we could separate our mlir from external/llvm-project commits. It should NOT have been squashed. 
It had a conflict in rebasing so I was going to do it manually.

**Comment by whchung** [comment]
@sjw36 sorry, should I hit "revert" button?

**Pull request merged**
