### PR TITLE
Add int8 E2E test cases

### PR DESCRIPTION
**Pull request by yiqian1**

### CODE REVIEW

**Review by jerryyin — CHANGES_REQUESTED** [review]
Thank you @yiqian1, I'm blocking this PR until all changes are done.

**Comment by krzysz00** [comment]
@yiqian1 Is there any particular reason this PR is running nightly tests?

**Comment by jerryyin** [comment]
@krzysz00 That's me kicking off nightly just so that we can do an initial regression on how well i8 is supported with existing implementation.

**Comment by krzysz00** [comment]
Ah

Could we perhaps run that test by hand off on one of the Lockharts instead?

**Comment by jerryyin** [comment]
@krzysz00 Won't be necessary since we already achieved full pass on int8 xdlops testing on resnet50. We'd flip back the switch and shoot for merging this PR so at least we have a good regression baseline.

**Review by jerryyin — APPROVED** [review]
LGTM

**Pull request merged**
