### PR TITLE
Miopen dialect opt step 22 : Force index type be 32-bits wide.

### PR DESCRIPTION
**Pull request by whchung**
Instead of hacking dataLayout string, use this trick converting MLIR dialects to LLVM-level dialect.

Ensure index type is 32-bits wide to reduce meaningless 32<->64 bit conversions ahead of load/store instructions.

For the config generated by `mlir-miopen-driver -p`:
Before: 521592 ns.
After: 407833 ns.

### CODE REVIEW

**Review by jerryyin — APPROVED** [review]
Interesting approach!

Would those existing type 32/64 conversions be automatically optimized away?

**Review by sjw36 — APPROVED** [review]
Looks good.

**Comment by whchung** [comment]
> Interesting approach!
> 
> Would those existing type 32/64 conversions be automatically optimized away?

yes. I discovered this some time ago. But what I did back then was pretty stupid (hack data layout string in `mlir-translate`). the approach in this PR is more elegant. we all need to study upstream logic better.

**Comment by whchung** [comment]
jenkins: retest this please.

**Pull request merged**
