### PR TITLE
Update Dockerfile to ROCm 4.3

### PR DESCRIPTION
**Pull request by krzysz00**
@okakarpa Are all the CI nodes updated to the 4.3 kernel driver?

### CODE REVIEW

**Comment by okakarpa** [comment]
> @okakarpa Are all the CI nodes updated to the 4.3 kernel driver?

The base rocm on private ci [http://rocmhead.amd.com:8080/] all of the nodes are at 4.3.1 except prj47-rack-48(gfx906)

For Public-CI[http://ml-ci.amd.com:21096/] most of the nodes Base rocm are at rocm-4.1

**Comment by whchung** [comment]
Applying `skip-ci` label for now to prevent it being accidentally merged. We want some dry runs on both private / public CI nodes before taking this.

**Comment by whchung** [comment]
@okakarpa in other projects have we tried run 4.3 docker instances on 4.1 batemetals?

**Comment by jerryyin** [comment]
@krzysz00 I assume you did reasonable amount of testing to make sure no regression happens?

**Review by jerryyin — APPROVED** [review]
Okay let's use CI to simplify our lives... If we find any regression in adopting this, we can dial back the ROCm release from jenkinsfile.

**Comment by krzysz00** [comment]
If anything, the 4.1 tagged image will still be around, so nothing should break from this PR - we'll just be creating 4.3 images going forward.

**Comment by okakarpa** [comment]
> @okakarpa in other projects have we tried run 4.3 docker instances on 4.1 batemetals?

Miopen did test that way for a while

**Pull request merged**
