### PR TITLE
Master updated to TOT

### PR DESCRIPTION
**Pull request by sjw36**

### CODE REVIEW

**Comment by whchung** [comment]
@jerryyin / @yiqian1 / @asleepzzz / @ltqin I'll hold off merging existing PRs before this one gets in.

**Comment by sjw36** [comment]
Part 1 of https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/77

**Comment by jerryyin** [comment]
I have never used master branch before. Could you elaborate what your overall plan is merging to `miopen-dialect`?

**Comment by sjw36** [comment]
Somehow a bad rebase. I am going to reset --hard from upstream.

**Pull request closed without merging**
