### PR TITLE
Rearrange non-xdlops memory operations, 12%-ish wrw perf boost

### PR DESCRIPTION
**Pull request by krzysz00**
Move the loads to the front of the loop, just like in the xdlops gemm. This leads to uniformity.

Most performance is flat or slightly improved, but we have somewhere around 10-18% performance improvement in wrw. Some forward-direction configs get worse, but it's not consistent which ones.

Here's a pair of performance runs from my Navi21 workstation, showing the wrw improvements.
[new-loop-order-perf.zip](https://github.com/ROCmSoftwarePlatform/rocMLIR/files/9833810/new-loop-order-perf.zip)

### CODE REVIEW

**Comment by jerryyin** [comment]
I noticed you have two measurements from the file:
 - What's the difference between the two?
 - Are those on heuristic configs, not from retuned results?

This looks very good. Reason I asked is because I find a couple of regressions on fwd configs. It'd be perfect if after re-tuning, the regression ones should be replaced by a different config.

**Review by jerryyin — APPROVED** [review]
I just double checked with the existing MIOpen/CK implementation. All of them uniformly followed the pattern of `load` -> `gemm` -> `store` in the loop.

**Comment by krzysz00** [comment]
These are heuristic results - and the two measurements are two independent runs of the benchmarks

**Comment by krzysz00** [comment]
And this is really showing we need to refresh our heuristic config list

And to update: it was backward data configs that regressed, not forward ones

**Pull request merged**
