### PR TITLE
Catch a lack of required arguments to the convolution generator.

### PR DESCRIPTION
**Pull request by krzysz00**
(this came out of running american-fuzzy-lop on `mlir-miopen-driver`, a process I'll document once I've refined it)

### CODE REVIEW

**Review by sjw36 — COMMENTED** [review]
These values can be set through the -conv-config cla as well..

Did you try this test: mlir/test/mlir-miopen-lib/populate_bwd.mlir

**Comment by krzysz00** [comment]
> 
> 
> These values can be set through the -conv-config cla as well..
> 
This check specifically excludes cases where the `--conv-config` argument is set

**Review by sjw36 — APPROVED** [review]
Ah, I see it now.  

Someday we should deprecate the driver options and convert all tests to conv-config so it is consistent with the C-API.

**Comment by krzysz00** [comment]
@sjw36 I'd actually argue for the opposite approach - that the library should be sent through a proper command-line parser and even that it might make sense to have MLIR be a separate binary instead of a static library.

**Comment by sjw36** [comment]
> @sjw36 I'd actually argue for the opposite approach - that the library should be sent through a proper command-line parser and even that it might make sense to have MLIR be a separate binary instead of a static library.

There is some merit to that since it does avoid the issues of global variables. But there is alot more overhead associated with spawning a new process to do compiles. LLVM is actively working on the reentrant problems.

**Comment by krzysz00** [comment]
Re avoiding the overhead, a `mlir-kernel-server` sort of thing could work: MIOpen spawns one process, keeps a pipe open, and then sends commands like `isApplicable`, `generate`, or `execute` down at us

**Pull request merged**
