### PR TITLE
Refactor end-to-end tests

### PR DESCRIPTION
**Pull request by krzysz00**
We've got a lot of copy-pasted `mlir-rocm-runner` calls running around, and also a bunch of tests that are the same thing except with different layouts/directions/datatypes. I've tried to put a dent into these issues with both `mlir-miopen-e2e-validate.sh` (runs all datatypes/layouts/directions for some arguments) and `run-conv-integration-test.sh` (which just abstracts out the mlir-rocm-runner call).

Some of the other e2e tests might also be refactorable, but I couldn't tell if they were at a glance, so I left them as is.

### CODE REVIEW

**Review by yiqian1 — APPROVED** [review]

**Comment by whchung** [comment]
Temporarily annotate this PR with `skip-ci` label to prevent it from using CI resources. Will restart CI once #396 is in.

**Comment by krzysz00** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@krzysz00 this PR is potentially causing nightly CI to fail, especially on e2e tests. I'm digging into the details.

From the look of it, those failing configs are all passing if executed individually. Therefore I'm leaning toward guessing the `parallel` command inside the bash script introduced in this PR caused some undesirable butterfly effects.

**Comment by whchung** [comment]
A hotfix is submitted at #401. I'm running local tests. Thus far it's much smoother, previously failing e2e tests are now passing. I'll post relevant logs onto #401 after the local run finishes.

**Comment by whchung** [comment]
@krzysz00 / @yiqian1 In case #401 can't be amended to fix the issue I'm inclined to revert #385 to restore nightly CI to a stable state so we can take #396.

**Comment by whchung** [comment]
Just filed PR #405 to temporarily revert this PR.

**Pull request merged**
