### PR TITLE
Update Jenkinsfile to use 4.1 image.

### PR DESCRIPTION
**Pull request by pcf000**

### CODE REVIEW

**Comment by whchung** [comment]
@jerryyin please help take a look at this PR

**Comment by jerryyin** [comment]
@whchung This change LGTM. With this submitted, our github CI will be bumped to ROCm 4.1.1. However, I'm not entirely sure about all the other jenkins files. I know about:
 - Jenkinsfile.downstream: github CI
 - Jenkinsfile.nightly: nightly e2e tests CI
 - Jenkinsfile.upstream: Not used

Are we actively using `Jenkinsfile.perf` and `Jenkinsfile.perf-gfx908`, or did you use it occasionally for performance runs?

----

Either ways, @pcf000, Now you can go ahead to bump all other jenkinsfiles in the same folder to ROCm 4.1.1 since this test round has make sure the version is good.

**Comment by whchung** [comment]
@pcf000 please change all variants of Jenkinsfile to ensure we use the same docker image

**Review by whchung — CHANGES_REQUESTED** [review]
@pcf000 Please help change all variants of Jenkinsfile under the directory so all pipelines use the same docker image.

**Comment by whchung** [comment]
Guess this is superseded by #158 ?

**Pull request closed without merging**
