### PR TITLE
Remove restrictions on backward data padding kernels

### PR DESCRIPTION
**Pull request by krzysz00**
The problem cases appear to work correctly now.

@whchung Do you have other examples of previously-broken cases?

### CODE REVIEW

**Comment by krzysz00** [comment]
I have run the new test manually and it passes

**Comment by krzysz00** [comment]
Fixes https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/297

**Comment by krzysz00** [comment]
Probably unrelated to https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/288 , https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/289,, https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/290 . These three issues seem to be configs that were worked around by pudding padding on the left in backwards data kernels. This is a "fix" we can revisit, but that's not this PR. 

Permits 
```
./bin/miopen-gen -pv -fil_layout=gkcyx -in_layout=ngchw -out_layout=ngkhw -groupsize=1 -batchsize=15 --padding_h=1 --padding_w=1 -in_channels=11 -out_channels=7 -in_h=5 -in_w=5 -fil_h=3 -fil_w=3 -p=false --conv_stride_h=2 --conv_stride_w=2 --operation=conv2d_bwd_data | ./bin/mlir-miopen-driver -c | rocm-run
Unranked Memref base@ = 0x22556b0 rank = 1 offset = 0 sizes = [1] strides = [1] data =
[1]
```
and therefore fixes https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/268 . 

Does **not** fix https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/259, which is currently a correctness bug. I think we'll need to hotfix in another error message to handle this one.

**Review by whchung — APPROVED** [review]
LGTM

**Pull request merged**
