### PR TITLE
Run MIOpen tests on pull requests

### PR DESCRIPTION
**Pull request by krzysz00**

### CODE REVIEW

**Review by whchung — APPROVED** [review]

**Comment by yiqian1** [comment]
Any reason why the PR's CIs don't use the one big Jenkinsfile?

**Comment by krzysz00** [comment]
We can't find a way to set the `canXdlops` parameter - see https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/314

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by krzysz00** [comment]
jenkins: retest this please

**Comment by sjw36** [comment]
We need this enalbed. @yiqian1 looks like it is waiting for your approval. Please expedite.

**Comment by krzysz00** [comment]
@sjw36 The approval is in, hopefully, but the reason this was taking forever to test is that the defaults in CMakeLists.txt reflect what we run nightly, not on PRs. I've pushed a new commit to address this.

**Comment by sjw36** [comment]
Sounds good. Thanks.

**Pull request merged**
