### PR TITLE
Add check for disjoint perf data to fix nightly

### PR DESCRIPTION
**Pull request by krzysz00**
Fixes https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/343

### CODE REVIEW

**Review by yiqian1 — APPROVED** [review]

**Comment by jerryyin** [comment]
@okakarpa  Please help take a look why 10.236.106.97 is not picking up this PR. This is a high priority fix.

@krzysz00 Could you work with Omkar to speed this up as CI nightly is failing consistently without it now.

**Comment by okakarpa** [comment]
> @okakarpa Please help take a look why 10.236.106.97 is not picking up this PR. This is a high priority fix.
> 
> @krzysz00 Could you work with Omkar to speed this up as CI nightly is failing consistently without it now.

The creds got expired i have updated the creds it should trigger the job

http://rocmhead:8080/job/mlir/view/change-requests/job/PR-382/1/console

**Comment by jerryyin** [comment]
@okakarpa Now looks like everything is failing directly as below two latest runs, could you take a look?

http://ml-ci.amd.com:21096/blue/organizations/jenkins/MLIR%2Fmlir/activity?branch=PR-382

**Comment by rocm-mici** [comment]
> @okakarpa Now looks like everything is failing directly as below two latest runs, could you take a look?
> 
> http://ml-ci.amd.com:21096/blue/organizations/jenkins/MLIR%2Fmlir/activity?branch=PR-382

it should be good now
http://ml-ci.amd.com:21096/blue/organizations/jenkins/MLIR%2Fmlir/detail/PR-382/6/pipeline

**Comment by jerryyin** [comment]
PR merged to retest in nightly context.

Also started a new run after this PR is merged: http://10.236.106.97:8080/blue/organizations/jenkins/mlir/detail/PR-382/3/pipeline/

Will monitor status.

**Pull request merged**
