### PR TITLE
Add rock.gemm support to rocmlir-gen with a MLIR-based verifier

### PR DESCRIPTION
**Pull request by krzysz00**
- Refactor rocmlir-gen to not pass a ConvConfig to places that don't need it, using the GenParams structure (which has an optional ConvConfig reference for convolution-specific code)
- Add support for generating GPU gemm kernels using rock.gemm and CPU gemm kernels using linalg.generic
- Add tests for the gemm validation code
- Add E2E tests, including a more comprehensive set of nightly tests and a smaller set of PR tests. This also means that PR testing now uses our new test-generation framework
  - Make such changes as were needed to the e2e test generation code to allow for gemm testing
- Cleanup of rocmlir-gen.cpp:
  - Made the value toggle option use an enum class to prevent accidental confusion or comparisons to int
  - Removed the "using namespace llvm;", allowing the removal of a _lot_ of mlir:: prefixes

This PR requires a nightly run of **just the shared library tests** to validate that no e2e tests broke.

Work remaining:
- https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/706
- https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/707

### CODE REVIEW

**Comment by krzysz00** [comment]
Nightly run http://rocmhead.amd.com:8080/blue/organizations/jenkins/MLIR%2Fmlir/detail/PR-821/3/pipeline - will update if it passed

**Comment by krzysz00** [comment]
Nightly shared libs with random passed, and does include the new e2e tests, so, barring some very weird failure with -rand 1, we're good to merge

**Comment by krzysz00** [comment]
Yep, that nightly passed

**Review by sjw36 — APPROVED** [review]
Looks good.

**Pull request merged**
