### PR TITLE
Port #291 to the one big Jenkisfile

### PR DESCRIPTION
**Pull request by krzysz00**
(In addition, fix the environment block to put the workspace at the
front of the library path, not the back)

### CODE REVIEW

**Comment by whchung** [comment]
@krzysz00 is the title incorrect, i think it should be #291 instead?

**Comment by krzysz00** [comment]
Yeah, the title's wrong - fixed

**Comment by jerryyin** [comment]
@krzysz00 Thanks for helping me with it! The change LGTM, could you do the following:
 - Remove `Jenkinsfile.miopen-test`
 - Point the nightly job at your one big jenkinsfile and get a passing record in there (Or also delete the jenkins job if your one big jenkinsfile is already running as expected)

Then once we merge your PR, the only thing left is to update the jenkins job such that it point to the right jenkins file/branch.

**Comment by krzysz00** [comment]
In order to get a passing test result, we'll want to merge this.

(and the way I see it, once we have a working nightly big Jenkinsfile job, we'll be able to delete jobs like the resnet50-nightly)

**Review by jerryyin — APPROVED** [review]
Please go ahead. Let me know if you need any help

**Pull request merged**
