### PR TITLE
Cleanup `test/rocmlir-driver/e2e_for_pr`

### PR DESCRIPTION
**Pull request by zhanglx13**
Tests in `e2e_for_pr` are converted into `test/e2e/PrResnet50.toml`.

### CODE REVIEW

**Review by krzysz00 — COMMENTED** [review]
Some of the tests we had were only present for particular operations, can you add some [[exnclude]] blocks?

**Comment by zhanglx13** [comment]
It's just the config to test the swizzles that has one operation. And I also added some [[exclude]] to only test the settings in the original file.

**Review by krzysz00 — APPROVED** [review]

**Comment by okakarpa** [comment]
restest

**Review by krzysz00 — COMMENTED** [review]
Hold on a moment ... weren't there `i8` and `bf16` tests?

**Comment by zhanglx13** [comment]
There were no i8 tests and bf16.mlir actually contains a single test with f16.
Do you want to add them? It's trivial since we have the PrResnet50.toml.

**Comment by krzysz00** [comment]
Ah, good to know. We can add them some other time.

**Pull request merged**
