### PR TITLE
Rename m/n_per_thread to m/n_per_wave

### PR DESCRIPTION
**Pull request by zjing14**
- Fix issue https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/121
- Rename m/n_per_thread to m/n_per_wave tuning parameters for xdlops

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
jenkins: test this please

**Review by whchung — APPROVED** [review]
LGTM

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by whchung** [comment]
@zjing14 see if you can improve this PR to a better level: write one unit test which tests the lowering process for XDLOPS path. Now we should *NOT* see `m/n_per_thread` after `-miopen-affix-params` / `-miopen-lowering-step2`, but should see `m/n_per_wave` in those passes.

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
jenkins: retest this please.

**Review by whchung — CHANGES_REQUESTED** [review]
@zjing14 please fix `clang-format`.

**Comment by whchung** [comment]
Jenkins: retest this please

**Review by whchung — APPROVED** [review]

**Pull request merged**
