### PR TITLE
Allow rock.buffer_{load,store} to support scalar memrefs

### PR DESCRIPTION
**Pull request by giuseros**
Fixes https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/827

### CODE REVIEW

**Comment by giuseros** [comment]
@sjw36 the `rocmlir-driver` command works now. Is there a way I can test it runs correctly (all tests - PR+nightly- pass)?

@krzysz00 Is there something more to be done here? I guess those guards in the `verify` function were there for a reason? But I wasn't able to understand if there is anything else to be changed.

**Comment by giuseros** [comment]
Ok, if I run `rocmlir-driver -c test.mlir` I get a segfault . I think this is related with this change :)

**Comment by sjw36** [comment]
You should be able to use one of the fusion tests and change the bias for instance to be passed as tensor<f32>. The e2e tests will validate the results with the cpu result.

**Review by krzysz00 — APPROVED** [review]
If we've confirmed that this does actually lower to something sensible, then yeah, approved.

**Comment by krzysz00** [comment]
What's the segfault?

**Comment by giuseros** [comment]
Ok, there were few things to change to make it work. I added few tests and I would like to verify it really works with a final integration test (in chat with @sjw36  to come up with one).

**Review by krzysz00 — APPROVED** [review]
Still approved, but if you could do some `git rebase -i` surgery to get this into two commits, one that's the external changes and one that's the internal ones, that'd be good - it'll make this easier to send this upstream

**Comment by giuseros** [comment]
Ok, I split the commit in three (llvm, rocm, integration). With the help of @sjw36  added also an integration test to check that everything works fine when we use scalar tensors.

**Comment by krzysz00** [comment]
LGTM

**Review by sjw36 — APPROVED** [review]
Looks good.

**Pull request merged**
