### PR TITLE
MLIR-435: fixed crash in multiple calls to MIOpenToTosaPass.

### PR DESCRIPTION
**Pull request by sjw36**
See ticket: https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/435

### CODE REVIEW

**Review by jungpark-mlir — APPROVED** [review]
All good

**Comment by sjw36** [comment]
This fixes the crash but does not fix the tests which were broken by the LLVM update. @pcf000 will follow up with a PR to restore the AbstractElementwise trait to Tosa Elementwise ops.

**Comment by pcf000** [comment]
> @pcf000 will follow up with a PR to restore the AbstractElementwise trait to Tosa Elementwise ops.

I can fix two partition-related tests, but tosa-to-miopen-relu.xmir.mlir looks like a binary-blob mismatch and I don't know where that's coming from.  It will stay XFAIL.

**Comment by jungpark-mlir** [comment]
Kicked the PR CI again, previous run failed because of a failure in MIOpenDriver test caused by gpu page fault. Likely to be occurred by external reason.

**Pull request merged**
