### PR TITLE
[HOTFIX] Adding mutex to serialize all API calls

### PR DESCRIPTION
**Pull request by jerryyin**
Adding an experiment to help triage integration test.

### CODE REVIEW

**Review by whchung — APPROVED** [review]
As a hotfix LGTM.

**Comment by whchung** [comment]
@sunway513 could you help log relevant test information from TensorFlow to log the validity of this PR? This PR can't be verified with existing CI jobs we have so far.

**Comment by sunway513** [comment]
I have validated this PR against TF Resnet50 convergence test, and I can confirm this PR could fix the following intermittent issue observed with the current MLIR main branch:
```
 2021-06-08 15:50:04.252458: I tensorflow/compiler/jit/xla_compilation_cache.cc:337] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2021-06-08 15:50:12.088994: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libMIOpen.so
python3: /root/llvm-project-mlir/llvm/include/llvm/ADT/DenseMap.h:408: void llvm::DenseMapBase<DerivedT, KeyT, ValueT, KeyInfoT, BucketT>::moveFromOldBuckets(BucketT*, BucketT*) [with DerivedT = llvm::DenseMap<mlir::TypeID, mlir::PassInfo, llvm::DenseMapInfo<mlir::TypeID
>, llvm::detail::DenseMapPair<mlir::TypeID, mlir::PassInfo> >; KeyT = mlir::TypeID; ValueT = mlir::PassInfo; KeyInfoT = llvm::DenseMapInfo<mlir::TypeID>; BucketT = llvm::detail::DenseMapPair<mlir::TypeID, mlir::PassInfo>]: Assertion `!FoundVal && "Key already in new map?
"' failed.                                                            
Fatal Python error: Aborted       
```

**Comment by sunway513** [comment]
Plus, there's no performance degradation observed with this PR, comparing to the mainline.

**Pull request merged**
