### PR TITLE
Fix handling of right padding

### PR DESCRIPTION
**Pull request by krzysz00**
When attempting to ensure that our convolution input always has enough
values to successfully apply the filter by implicitly adding padding,
we were failing to include the already-specified right padding in the
new right padding value.

This commit fixes that issue and adjusts the tests that depended on it.

### CODE REVIEW

**Comment by krzysz00** [comment]
(currently running nightly tests on this change)

**Comment by krzysz00** [comment]
Nightlies pass with this change

**Review by whchung — COMMENTED** [review]
The new logic indeed addresses the issue in the existing logic.

@sjw36 it'd be good if you can take a look at this PR and have the final approval.

**Review by sjw36 — APPROVED** [review]
Looks good. ( as long as we have adequate coverage ..)

**Pull request merged**
