### PR TITLE
Refactor jenkinsfile

### PR DESCRIPTION
**Pull request by okakarpa**
Refactor MIOpen-build stages that are needed by both performance tests and MIOpen validations

Make E2E tests with fixed data and random data in parallel to reduce the execution time.

Increase the timeout limit for tuning MLIR kernels.

Test CIs:
nightly+sharedLib+staticLib+perfTest
http://ml-ci.amd.com:21096/blue/organizations/jenkins/MLIR%2Frefactor-Jenkinsfile/detail/refactor-Jenkinsfile/24/pipeline

nightly + perfTest
http://ml-ci.amd.com:21096/blue/organizations/jenkins/MLIR%2Frefactor-Jenkinsfile/detail/refactor-Jenkinsfile/20/pipeline

nightly+staticLib
http://ml-ci.amd.com:21096/blue/organizations/jenkins/MLIR%2Frefactor-Jenkinsfile/detail/refactor-Jenkinsfile/19/pipeline

nightly+sharedLib
http://ml-ci.amd.com:21096/blue/organizations/jenkins/MLIR%2Frefactor-Jenkinsfile/detail/refactor-Jenkinsfile/18/pipeline

This is the same PR as #399. I had to close the old one and open a new PR in order to make the status checks work for the new stages.

### CODE REVIEW

**Review by krzysz00 — APPROVED** [review]
Sorry for forgetting this is here, approved

**Comment by whchung** [comment]
Let's hold off merging this until #396 lands.

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by whchung** [comment]
this PR is failing due to `clang-format` issue. @okakarpa , please help check CI log at:

http://10.236.106.97:8080/blue/organizations/jenkins/mlir/detail/PR-404/4/pipeline

**Comment by okakarpa** [comment]
> this PR is failing due to `clang-format` issue. @okakarpa , please help check CI log at:
> 
> http://10.236.106.97:8080/blue/organizations/jenkins/mlir/detail/PR-404/4/pipeline

i am not sure how can i  be helpful with this error

[2021-10-19T17:35:43.549Z]     mlir/tools/mlir-rocm-runner/mlir-rocm-runner.cpp

[2021-10-19T17:35:51.726Z] Please format your changes with clang-format by running `git-clang-format HEAD^` or applying patch.

script returned exit code 1

**Comment by whchung** [comment]
@okakarpa let me try checkout this branch and see how we can do about it. the same symptom seems to apply one several other PRs.

**Pull request merged**
