### PR TITLE
Miopen dialect opt step9 : Refactor lowering logic of `threadwise_copy` and `threadwise_copy_v2`.

### PR DESCRIPTION
**Pull request by whchung**
Compartmentalize lowering logic of `miopen.threadwise_copy` and `miopen.threadwise_copy_v2` to make it modular and easier to support vector loads / stores, and in the next PR `miopen.threadwise_load` and `miopen.threadwise_store` would also reuse the same modules.

### CODE REVIEW

**Comment by whchung** [comment]
After close scrutiny from @zjing14 and @asroy , existing implementation computing index diff maps needs to be revised and break into smaller PRs. Closing this PR for now.

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by whchung** [comment]
@asroy I've major re-worked this PR to decompose lowering logic for `threadwise_copy` and `threadwise_copy_v2` into smaller reusable pieces. It would help us in PR #200 to use these pieces to build `threadwise_load` and `threadwise_store`.

We will review this PR tomorrow (6/8/2021), and hopefully I can finish PR #200 by then.

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by whchung** [comment]
@okakarpa wondering why this PR won't be tested by Jenkins, even though I asked the bot to retest it (I also said please...)?

**Review by asroy — APPROVED** [review]

**Comment by whchung** [comment]
Will wait until a round of CI test is completed before taking this PR.

@okakarpa how to force execute a CI run on `default` target? for `rocm-head-ci` it seems a job is running.

**Comment by whchung** [comment]
jenkins: retest default please.

**Comment by whchung** [comment]
@okakarpa it seems after I hit `update branch` button things start getting back to normal.

**Comment by okakarpa** [comment]
> @okakarpa it seems after I hit `update branch` button things start getting back to normal.

can you please be more specifc not sure i understand

**Comment by whchung** [comment]
> > @okakarpa it seems after I hit `update branch` button things start getting back to normal.
> 
> can you please be more specifc not sure i understand

i couldn't get `default` CI target be triggered for this particular PR. but it seems after I hit `update branch` to merge with the tip of `miopen-dialect` the `default` target start to build.

**Comment by whchung** [comment]
CI job on `default` captured 2 failing cases. Looking into that.

**Comment by whchung** [comment]
Fix an important bug where we inadvertently pass a `SmallVector` by copy instead of by reference.

**Pull request merged**
