### PR TITLE
Lower math library functions to libm

### PR DESCRIPTION
**Pull request by giuseros**
fixes https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/763

### CODE REVIEW

**Comment by manupak** [comment]
Can we run a nightly on this ?

**Comment by giuseros** [comment]
Hi @manupak , yes, but before running it I wanted to make sure that the change I made was ok

**Review by krzysz00 — COMMENTED** [review]
This seems like a reasonable change for host code. I'll approve once we know it works

**Review by krzysz00 — APPROVED** [review]
Approved

**Pull request merged**
