### PR TITLE
Gracefully not fail when transpose cannot be folded.

### PR DESCRIPTION
**Pull request by manupak**
There can be scenarios where tp cant be folded
such as a reshape collasing non-contigous dims
following a transpose.

This commit fixes/reverts op creations if the folding is not successful.

### CODE REVIEW

**Comment by manupak** [comment]
somewhat related discussion : https://github.com/ROCmSoftwarePlatform/rocMLIR/discussions/1054

**Review by krzysz00 — COMMENTED** [review]
Wait, so what's this actually fixing?

**Comment by manupak** [comment]
This is fixing that bug of prematurely creating new collapse shape ops while the pass can still fail to fold.

**Review by krzysz00 — APPROVED** [review]
Yeah, makes sense, approved

**Comment by manupak** [comment]
Thanks @krzysz00!

**Pull request merged**
