### PR TITLE
Bump dockerfile to ROCm 5.2.3

### PR DESCRIPTION
**Pull request by jerryyin**

### CODE REVIEW

**Comment by krzysz00** [comment]
Have the MIOpen dependencies changed recently, and should we bump that commit as well while we're here?

**Comment by zhanglx13** [comment]
I am just curious about is there a way to `wget` the latest MIOpen instead of maintaining a commit? Or is there a good reason to do so?

**Comment by jerryyin** [comment]
@zhanglx13 That's actually a good idea. By looking at when the docker is populated, we know which version of MIOpen dependency we get.

**Review by zhanglx13 — APPROVED** [review]

**Review by krzysz00 — APPROVED** [review]
@zhanglx13 , great idea with the wget! I'm in favor of all of this

**Pull request merged**
