### PR TITLE
Fix converting tosa.clamp and tosa.relu to linalg

### PR DESCRIPTION
**Pull request by jungpark-mlir**
Upstream fix

### CODE REVIEW

**Review by krzysz00 — APPROVED** [review]
Can I ask that we use the commit message from upstream and indicate which upstream commit this was?

**Comment by jungpark-mlir** [comment]
@krzysz00 This is to fix upstream. I actually have never tried to make a commit upstream, can you please help me finding how to do it? By the way, I'm off and come back next Monday.

**Review by krzysz00 — CHANGES_REQUESTED** [review]
I'm going to un-approve because I'd like to see a more throrough explanation of what the bug is and how this fixes it so we can send this upstream

**Comment by krzysz00** [comment]
And I can definitely walk you through the upstreaming process

**Comment by krzysz00** [comment]
I approve of the change, and it is a legitimate bugfix

However, I'd like you to please do some repo surgery to get this into one clean commit, ideally before we merge it in, so it's easy to cherry-pick upstream

`git rebase -i miopen-dialect` will be your friend here, with the actions you want being "reword" and "fixup", respectively

**Comment by sjw36** [comment]
@jungpark-mlir formatting failure..

**Comment by sjw36** [comment]
@krzysz00 still marked as "changes required"

**Review by sjw36 — APPROVED** [review]
Looks good.

**Review by krzysz00 — APPROVED** [review]
Thanks for cleaning up the commit - approved!

**Pull request merged**
