### PR TITLE
[CI][navi21] Enable navi21 codepath in weekly CI

### PR DESCRIPTION
**Pull request by zhanglx13**

### CODE REVIEW

**Review by krzysz00 — COMMENTED** [review]
Do we have enough Navi nodes that PR, nightly, and weekly won't start getting bottlenecked on this?

(code-wise, LGTM)

**Comment by zhanglx13** [comment]
We have 3 workstations available for PR CI right now (since I am actively using another one for testing). I am also testing the server nodes. And if they works fine, we will have two mode nodes for CI. So I think we have enough.

**Review by krzysz00 — APPROVED** [review]
Approved, but please keep an eye on CI congestion

**Review by krzysz00 — APPROVED** [review]
Approved, but please keep an eye on CI cong

**Pull request merged**
