### PR TITLE
Revert "Computer more of xdlops addressing at compile time."

### PR DESCRIPTION
**Pull request by jerryyin**
For test regression

### CODE REVIEW

**Comment by jerryyin** [comment]
Note: CI run [here ](http://rocmhead.amd.com:8080/blue/organizations/jenkins/mlir/detail/PR-433/1/pipeline/85) shows that this PR will fix the nightly CI failure [here](http://10.236.106.97:8080/blue/organizations/jenkins/mlir-nightly-all/detail/mlir-nightly-all/155/pipeline). Therefore this PR shoots for merge.

@krzysz00 Please test/fix/resubmit the #431 if necessary.

**Comment by krzysz00** [comment]
@jerryyin How does the linked CI run show that this fixes the regression?

**Comment by jerryyin** [comment]
@krzysz00 Refer to "Test MIOpen Config with tuning" vs (almost) the tip of MIOpen [here](http://rocmhead.amd.com:8080/blue/organizations/jenkins/mlir/detail/PR-414/23/pipeline/).

**Review by whchung — APPROVED** [review]
The original PR is logically correct and I don't understand why it could fail the tuning process. But we have to respect the logs collected by CI. Approving the PR hereby.

**Comment by krzysz00** [comment]
Something I found while debugging:
```
./bin/mlir-miopen-driver --in_layout=nchw --fil_layout=kcyx --out_layout=nkhw --batchsize 256 --groupsize 1 --in_channels 512 --in_h 16 --in_w 16 --fil_h 3 --fil_w 3 --out_channels 512 --padding_h 0 --padding_w 0 --conv_stride_h 2 --conv_stride_w 2 --dilation_h 1 --dilation_w 1 --operation conv2d -t fp32 -miopen-affix-params -miopen-lowering -miopen-affine-transform -miopen-lowering-step2 -x2
```
and
```
./bin/mlir-miopen-driver --in_layout=nchw --fil_layout=kcyx --out_layout=nkhw --batchsize 256 --groupsize 1 --in_channels 512 --in_h 16 --in_w 16 --fil_h 3 --fil_w 3 --out_channels 512 --padding_h 0 --padding_w 0 --conv_stride_h 2 --conv_stride_w 2 --dilation_h 1 --dilation_w 1 --operation conv2d -t fp32 -c -ph -x2
```

generate *identical* output before and after the revert. That doesn't make any sense. (the parameters there were taken from last night's failing nightly)

@jerryyin @whchung Any thoughts on what might be happening/not-happening here?

**Comment by krzysz00** [comment]
My current theory is that the ops the pre-431 code generates aren't used anywhere and so get dropped from the output, but that would mean that the miopen integration shouldn't fail. Is there some meaningful difference in how we perform lowering between these integration tests and the mlir-miopen-driver/mlir-rocm-runner combo?

**Comment by jerryyin** [comment]
@krzysz00 I think you are a number of steps ahead in the debugging sequence. Let's start from the point of where regression occurs, are you able to reproduce the nightly CI failure just inside of MIOpenDriver? This at least help align up on all the environment/build.

If yes, then the next meaningful step is to see if the kernel ISA are the same before and after using `mlir-miopen-lib-test.cpp`

**Pull request merged**
