### PR TITLE
Add error check for unsupported WMMA configuration (e.g., kouter*kpack < 16)

### PR DESCRIPTION
**Pull request by giuseros**
This is a check that is present in the `mfma` branch but I probably forgot to add it in the `wmma` branch.

### CODE REVIEW

**Comment by giuseros** [comment]
Fixes https://github.com/ROCmSoftwarePlatform/rocMLIR-internal/issues/1078

**Comment by yiqian1** [comment]
Have you tried this change with the develop branch? I ran the test case in the issue#1078 and got the error "Getting kernel count failed". With your branch, rocmlir-driver had lowering failure. However, both failures happened at the check wmmaInsn.isCoherentWithK().

**Comment by giuseros** [comment]
> Have you tried this change with the develop branch? I ran the test case in the issue#1078 and got the error "Getting kernel count failed". With your branch, rocmlir-driver had lowering failure. However, both failures happened at the check wmmaInsn.isCoherentWithK().

Hi Yi, yes, this is the goal of the PR. Wmma perf configs where `kPerBlock  <16` and `kPack==1` should fail, in the same way they fail for mfma when `kPerBlock < attr.k_base` . The perf config in https://github.com/ROCmSoftwarePlatform/rocMLIR-internal/issues/1078 is indeed: `256,128,8,64,128,1,1,1` and `kPerBlock=8<16`

**Comment by yiqian1** [comment]
> Hi Yi, yes, this is the goal of the PR. Wmma perf configs where kPerBlock  <16 and kPack==1 should fail, in the same way they fail for mfma when kPerBlock < attr.k_base . The perf config in https://github.com/ROCmSoftwarePlatform/rocMLIR-internal/issues/1078 is indeed: 256,128,8,64,128,1,1,1 and kPerBlock=8<16

I think we should not use this perf_config for wmma. This is an E2E test and should not fail. I don't remember why we had this test in the first place. We probably can remove this test. But for this PR, I'd suggest use an applicable perf_config, or mark it as XFAIL for wmma, or simply disable this test for wmma.

**Comment by giuseros** [comment]
> But for this PR, I'd suggest use an applicable perf_config, or mark it as XFAIL for wmma, or simply disable this test for wmma.

Do you want me to do in this PR? Or are you going to do that while enabling tests for wmma?

**Comment by krzysz00** [comment]
This seems like a reasonable check to add and will enable better tuning for MIGraphX.

**Comment by yiqian1** [comment]
> > But for this PR, I'd suggest use an applicable perf_config, or mark it as XFAIL for wmma, or simply disable this test for wmma.
> 
> Do you want me to do in this PR? Or are you going to do that while enabling tests for wmma?

No need to address it in this PR. Apologies for the confusion, as I had assumed wmma was already enabled (given my recent work on it), and this PR would cause failure of the nightly job.

**Review by yiqian1 — APPROVED** [review]

**Pull request merged**
