### PR TITLE
Cosmetic change in SQLite config process. NFC

### PR DESCRIPTION
**Pull request by whchung**

### CODE REVIEW

**Comment by whchung** [comment]
I was trying to study if it's possible to disable SQLite-related unit tests if SQLite is not installed. But turns out we have to change top-level CMake scripts. Therefore it's not included in this PR.

**Review by jerryyin — APPROVED** [review]

**Comment by jerryyin** [comment]
@whchung Donot include `-DMLIR_ENABLE_SQLITE=1` will disable SQLite. If we do care about the functionality of this, I can add a pipeline stage to make sure it get tested.

**Comment by whchung** [comment]
@jerryyin if `-DMLIR_ENABLE_SQLITE=0`, 3 tests in `Dialect/MIOpen/Tuning/` would fail.

**Comment by jerryyin** [comment]
@whchung Yes, that is expected because those 3 checks for successful db connection. If we don't enable sqlite configuration, than all db related logic will be gone, therefore no db connection. For now, you may tolerate the 3 failures in that condition. I would need to figure out conditional pass/fail under different build configs in the future.

**Comment by whchung** [comment]
ok it's fine with me.

**Pull request merged**
