### PR TITLE
Don't install MIOpen dependencies in CI

### PR DESCRIPTION
**Pull request by krzysz00**

### CODE REVIEW

**Review by jerryyin — APPROVED** [review]
Wired, why does the diff still include `Dockerfile.rocm` after you have merged?

**Comment by pcf000** [comment]
I thought it would be more complicated.  Assuming the int8-perf-whatever branch isn't bothered, this looks good to me.

**Review by pcf000 — APPROVED** [review]

**Comment by krzysz00** [comment]
I went and rebased onto `miopen-dialect` to fix the issue

**Comment by pcf000** [comment]
The ml-ci.amd.com failure is

CMake Error at CMakeLists.txt:53 (find_package):
  Could not find a configuration file for package "ROCM" that is compatible
  with requested version "0.7.3".

  The following configuration files were considered but not accepted:

    /opt/rocm/share/rocm/cmake/ROCMConfig.cmake, version: 0.6.1
    /opt/rocm-5.0.1/share/rocm/cmake/ROCMConfig.cmake, version: 0.6.1

I didn't look very hard, but I remember that one of the differences between the two MIOpen branches was the rocm.cmake version.

**Pull request merged**
