### PR TITLE
Miopen dialect opt step20 : Switch from workgroup barrier to LDS barrier.

### PR DESCRIPTION
**Pull request by whchung**
Add a FIXME comment in the undesirable barrier within xdlops_gemm_v2 op.

### CODE REVIEW

**Comment by whchung** [comment]
jenkins: retest this please.

**Comment by whchung** [comment]
@okakarpa the CI node for `gfx908` is also acting funky:

http://10.236.106.97:8080/blue/organizations/jenkins/mlir/detail/PR-244/5/pipeline

**Comment by okakarpa** [comment]
> @okakarpa the CI node for `gfx908` is also acting funky:
> 
> http://10.236.106.97:8080/blue/organizations/jenkins/mlir/detail/PR-244/5/pipeline

For internal ci(rocmhead) there seems to be a problem with rocm on one of gfx908 node  and needs a cold reboot from onsite i have disconnected from the the CI for now please retest now it shouldn't be causing any issues

**Comment by whchung** [comment]
jenkins: retest this please.

**Review by asroy — APPROVED** [review]

**Comment by whchung** [comment]
@okakarpa it's still not working:

http://10.236.106.97:8080/blue/organizations/jenkins/mlir/detail/PR-244/6/pipeline

**Comment by okakarpa** [comment]
> http://10.236.106.97:8080/blue/organizations/jenkins/mlir/detail/PR-244/6/pipeline

It seems like the build folder still exists with root permissions on the baremetal node and the post-condition which applied in jenkinsfile unable to delete the folder, since it's owned by root causing the disk space to be consumed entirely.I will add additional cronjobs for the nodes to clear out the workspace, as of now i have manually deleted the workspace folder and retriggered the job.

**Comment by whchung** [comment]
@yiqian1 Wondering if it's possible to trigger a nightly CI job on a particular PR? I used workgroup barrier instead of LDS barriers some time ago to prevent incorrect compiler optimizations from happening. But it seems time to reinstate it. But I'd like a nightly CI to validate it first.

**Pull request merged**
