### PR TITLE
XDLOPS support logic

### PR DESCRIPTION
**Pull request by whchung**
- fp32 / fp16
- forward / backward data / backward weight

- -x2 flag in mlir-miopen-driver.

### CODE REVIEW

**Comment by jerryyin** [comment]
Awesome, what a huge review. Give me a little bit of time to review this. I'll try to leave comments by end of Friday if there's any.

**Comment by jerryyin** [comment]
jenkins retest this please

**Comment by whchung** [comment]
@jerryyin if you are okay with it I'd like to take this PR so further CI checks would start check XDLOPS-related tests. you can of course continue review this PR and we can amend the codes.

**Comment by jerryyin** [comment]
Please go ahead! I took a very brief study hoping to gain more understanding of your recent work but was not able to follow due to the volume of changes :-p.

**Pull request merged**
