### PR TITLE
Fixing clang compatibility by removing lambda class memeber static initialization

### PR DESCRIPTION
**Pull request by jerryyin**
This fixed the incompatibility of the compiler error thrown from 

> CXX=/usr/bin/clang++-10
CC=/usr/bin/clang-10

of

> /home/swaters/iwa/rocMLIR.0/mlir/lib/Dialect/Rock/IR/MfmaInsnGroup.cpp:21:47: error: declaration requires a global destructor [-Werror,-Wglobal-constructors]
const llvm::StringMap<MfmaInsnInfo> MfmaInsn::mfmaInsnInfoMap = [] {
                                              ^
/home/swaters/iwa/rocMLIR.0/mlir/lib/Dialect/Rock/IR/MfmaInsnGroup.cpp:66:47: error: declaration requires a global

I used lambda local static variable instead.

### CODE REVIEW

**Review by giuseros — APPROVED** [review]
LGTM

**Comment by jerryyin** [comment]
Full pass in nightly: http://rocmhead.amd.com:8080/blue/organizations/jenkins/MLIR%2Fmlir/detail/PR-926/8/pipeline/782/

Full pass in weekly: http://rocmhead.amd.com:8080/blue/organizations/jenkins/MLIR%2Fmlir/detail/PR-926/7/pipeline/317/

**Comment by giuseros** [comment]
@jerryyin I already merged it because I was having this exact same problem and your PR sorted it out :)

**Comment by jerryyin** [comment]
@giuseros Thank you. At the time I write my comment, the webpage I had open is still in yesterday's state. I just realize it is merged after a refresh of this page.

**Pull request merged**
