### PR TITLE
Cherry-pick remaining PRs from miopen-dialect-old

### PR DESCRIPTION
**Pull request by sjw36**
ROCmSoftwarePlatform/llvm-project-mlir#57
ROCmSoftwarePlatform/llvm-project-mlir#56

Also removed the code-object-v3 setting, now default.

Resolves https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/86

### CODE REVIEW

**Comment by jerryyin** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@sjw36 / @jerryyin , looking at CI log :

http://ml-ci.amd.com:21096/job/MLIR/job/MLIR-downstream-unit-test/2868/console

it appears not all jenkins workspaces have been wiped out yet.

**Comment by jerryyin** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
http://ml-ci.amd.com:21096/job/MLIR/job/MLIR-downstream-unit-test/2869/console

seems to be running. let's see what happens.

**Comment by sjw36** [comment]
@whchung , @jerryyin , @yiqian1 
Would be good to review the last 5 commits (mine) to see what was needed for this rebase and make sure I did it right.

**Comment by sjw36** [comment]
Accidentally pushed Jack's commits that I cherry picked. Let's go ahead and merge these if all goes well.

**Pull request merged**
